code

equ trap_Print                            -1
equ trap_Error                            -2
equ trap_Milliseconds                     -3
equ trap_Cvar_Register                    -4
equ trap_Cvar_Update                      -5
equ trap_Cvar_Set                         -6
equ trap_Cvar_VariableIntegerValue        -7
equ trap_Cvar_VariableStringBuffer        -8
equ trap_Cvar_LatchedVariableStringBuffer -9
equ trap_Argc                             -10
equ trap_Argv                             -11
equ trap_SendConsoleCommand               -12
equ trap_FS_FOpenFile                     -13
equ trap_FS_Read                          -14
equ trap_FS_Write                         -15
equ trap_FS_Rename                        -16
equ trap_FS_FCloseFile                    -17
equ trap_FS_GetFileList                   -18
equ trap_LocateGameData                   -19
equ trap_DropClient                       -20
equ trap_SendServerCommand                -21
equ trap_LinkEntity                       -22
equ trap_UnlinkEntity                     -23
equ trap_EntitiesInBox                    -24
equ trap_EntityContact                    -25
equ trap_EntityContactCapsule             -26
equ trap_Trace                            -27
equ trap_TraceNoEnts                      -27
equ trap_TraceCapsule                     -28
equ trap_TraceCapsuleNoEnts               -28
equ trap_PointContents                    -29
equ trap_SetBrushModel                    -30
equ trap_InPVS                            -31
equ trap_InPVSIgnorePortals               -32
equ trap_SetConfigstring                  -33
equ trap_GetConfigstring                  -34
equ trap_SetConfigstringRestrictions      -35
equ trap_SetUserinfo                      -36
equ trap_GetUserinfo                      -37
equ trap_GetServerinfo                    -38
equ trap_AdjustAreaPortalState            -39
equ trap_AreasConnected                   -40
equ trap_UpdateSharedConfig               -41
equ trap_BotAllocateClient                -42
equ trap_BotFreeClient                    -43
equ trap_GetUsercmd                       -44
equ trap_GetEntityToken                   -45
equ trap_RealTime                         -46
equ trap_SnapVector                       -47
equ trap_SendGameStat                     -48
equ trap_AddCommand                       -49
equ trap_RemoveCommand                    -50
equ trap_GetTag                           -51
equ trap_LoadTag                          -52
equ trap_RegisterSound                    -53
equ trap_GetSoundLength                   -54
equ trap_Parse_AddGlobalDefine            -55
equ trap_Parse_LoadSource                 -56
equ trap_Parse_FreeSource                 -57
equ trap_Parse_ReadToken                  -58
equ trap_Parse_SourceFileAndLine          -59
equ trap_BotGetServerCommand              -60
equ trap_AddPhysicsEntity                 -61
equ trap_AddPhysicsStatic                 -62
equ trap_SendMessage                      -63
equ trap_MessageStatus                    -64
equ trap_SQL_RunQuery                     -65
equ trap_SQL_FinishQuery                  -66
equ trap_SQL_NextRow                      -67
equ trap_SQL_RowCount                     -68
equ trap_SQL_GetFieldbyID                 -69
equ trap_SQL_GetFieldbyName               -70
equ trap_SQL_GetFieldbyID_int             -71
equ trap_SQL_GetFieldbyName_int           -72
equ trap_SQL_FieldCount                   -73
equ trap_SQL_CleanString                  -74
equ trap_RSA_GenerateMessage              -75
equ memset                                -301
equ memcpy                                -302
equ memcmp                                -303
equ strncpy                               -304
equ sin                                   -305
equ cos                                   -306
equ asin                                  -307
equ atan2                                 -308
equ sqrt                                  -309
equ floor                                 -313
equ ceil                                  -314
equ testPrintInt                          -315
equ testPrintFloat                        -316
