/*
===========================================================================

Unvanquished GPL Source Code
Copyright (C) 2012 Unvanquished Developers

This file is part of the Unvanquished GPL Source Code (Unvanquished Source Code).

Unvanquished Source Code is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Unvanquished Source Code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Unvanquished Source Code.  If not, see <http://www.gnu.org/licenses/>.

In addition, the Unvanquished Source Code is also subject to certain additional terms.
You should have received a copy of these additional terms immediately following the
terms and conditions of the GNU General Public License which accompanied the Unvanquished
Source Code.  If not, please request a copy in writing from id Software at the address
below.

If you have questions concerning this license or the applicable additional terms, you
may contact in writing id Software LLC, c/o ZeniMax Media Inc., Suite 120, Rockville,
Maryland 20850 USA.

===========================================================================
*/

#ifndef ROCKETFORMCONTROLSELECT_H
#define ROCKETFORMCONTROLSELECT_H

#include "../cg_local.h"
#include <RmlUi/Core.h>

class CvarElementFormControlSelect : public Rml::ElementFormControlSelect, public Rml::EventListener
{
public:
	CvarElementFormControlSelect( const Rml::String &tag ) :
			Rml::ElementFormControlSelect( tag ),
			owner( nullptr ),
			ignore_value_change( false ) { }

	void OnAttributeChange( const Rml::ElementAttributes &changed_attributes ) override
	{
		Rml::ElementFormControlSelect::OnAttributeChange( changed_attributes );
		Rml::ElementAttributes::const_iterator it = changed_attributes.find( "cvar" );
		if ( it != changed_attributes.end() )
		{
			cvar = it->second.Get<Rml::String>();
			// Don't try to compare values when none have been added yet. This will happen because
			// attributes are parsed before children are added, so when this code runs initially,
			// we will never have any children.
			if ( GetNumOptions() > 0 )
			{
				UpdateValue();
			}
		}
	}

	void OnChildAdd( Element *child ) override
	{
		Rml::ElementFormControlSelect::OnChildAdd( child );
		if ( child == this )
		{
			// Need to cache this because it is not available
			// when this element is being removed
			owner = GetOwnerDocument();
			if ( owner == nullptr )
			{
				return;
			}
			owner->AddEventListener( Rml::EventId::Show, this );
			owner->AddEventListener( Rml::EventId::Change, this );
		}
	}

	void OnChildRemove( Element *child ) override
	{
		Rml::ElementFormControlSelect::OnChildRemove( child );
		if ( child == this && owner )
		{
			owner->RemoveEventListener( Rml::EventId::Show, this );
			owner->RemoveEventListener( Rml::EventId::Change, this );
		}
	}

	void ProcessEvent( Rml::Event &event ) override
	{
		if ( !owner )
		{
			return;
		}
		if ( !cvar.empty() )
		{
			if ( owner == event.GetTargetElement() && event == Rml::EventId::Show )
			{
				UpdateValue();
			}
			else if ( this == event.GetTargetElement() && event == Rml::EventId::Change )
			{
				if ( ignore_value_change )
				{
					return;
				}
				Cvar::SetValue( cvar.c_str(), GetValue().c_str() );
				Cvar::AddFlags( cvar.c_str(), Cvar::USER_ARCHIVE );
			}
		}
	}

	void UpdateValue()
	{
		Rml::String cvarValue = Cvar::GetValue( cvar.c_str() );
		for ( int i = 0; i < GetNumOptions(); ++i )
		{
			Rml::Element* e = GetOption(i);
			Rml::String value = e->GetAttribute<Rml::String>( "value", Rml::String() );
			if ( value == cvarValue )
			{
				ignore_value_change = true;
				SetSelection( i );
				ignore_value_change = false;
				return;
			}
		}
		// No matches...Let's add an option for our current value.
		Add( Str::Format( "Custom Value (%s)", cvarValue ), cvarValue, 0, false );
		ignore_value_change = true;
		SetSelection( 0 );
		ignore_value_change = false;
	}

private:
	Rml::String cvar;
	Rml::Element *owner;

	// Set to true during change events generated in UpdateValue to avoid unwanted Cvar::SetValue
	// calls. False if the change event was generated by the user clicking.
	bool ignore_value_change;
};

#endif
