# Documentation: https://wiki.unvanquished.net/wiki/Continuous_integration

only_commits:
  files:
    - .appveyor.yml
    # The rest of this list should stay in sync with azure-pipelines.yml
    - daemon/
    - libs/
    - src/
    - .gitmodules
    - CMakeLists.txt
    - '*.cmake'
    - macosx/
    - tools/cbse/

image: Visual Studio 2019

environment:
  matrix:
    - COMPILER: msvc
      COMPILER_VERSION: "16.0" # Visual Studio 2019
      TARGET: x86
      GENERATOR: "NMake Makefiles"

matrix:
  fast_finish: false

configuration: Debug

build:
  parallel: true

before_build:
  - curl -sS https://gitlab.com/illwieckz/git-checkout-modules/raw/master/git-checkout-modules -o git-checkout-modules
  # The git-checkout-modules command below is normally equivalent to 'git submodule update --init --recursive',
  # but in the case that the branch name ends with '/sync' it tries to find branches with the same name.
  - bash git-checkout-modules
    --update
    --sub-ref=%APPVEYOR_REPO_BRANCH%:has=/sync$
    --sub-ref=%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%:has=/sync$
    --print
  - python --version
  - python -m pip install -r tools/cbse/requirements.txt --upgrade

build_script:
  - cmd: cmake --version
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  # We don't need iteration; the for loop executes only once. But the function for resolving
  # something in PATH (like 'which') is in the FOR command
  - cmd: FOR %%p IN (python.exe) DO set firstPython=%%~$PATH:p
  - cmd: cmake -DUSE_PRECOMPILED_HEADER=0 -DUSE_WERROR=1 -DBE_VERBOSE=1 -G "NMake Makefiles"
         -DBUILD_CLIENT=0 -DBUILD_TTY_CLIENT=0 -DBUILD_SERVER=0 -DBUILD_GAME_NACL=0
         -DCMAKE_BUILD_TYPE=Debug -DCBSE_PYTHON_PATH=%firstPython%
         -H. -Bbuild
  - cmd: cmake --build build
