[gameinfo]
# Display name, can contain special characters,
# like "Unvanquished", "Smokin' Guns", etc.
name = "Unvanquished"
# Version string, usually in the form "0.52", "1.2.3", etc.
version = "0.56.1"
# XDG Application ID, used to by XDG desktops to associate
# windows of running binaries with their icons.
# It's written in the reverse-domain form
# like "net.unvanquished.Unvanquished".
appId = "net.unvanquished.Unvanquished"
# Directory base name where user data will be stored on Windows.
# For example with "Unvanquished" it will store data in
#     C:\Users\<username>\My Games\Unvanquished
# It's common to find capitalized names and even white spaces,
# but you may prefer to avoid special characters.
windowsDirName = "Unvanquished"
# Directory base name where user data will be stored on macOS.
# For example with "Unvanquished" it will store data in
#   /Users/<username>/Library/Application Support/Unvanquished
# It's common to find capitalized names and even white spaces
# but you may prefer to avoid special characters.
#
# Some may prefer directory names in the form
# of "net.unvanquished.Unvanquished", this is not unusual.
macosDirName = "Unvanquished"
# Directory base name where user data will be stored on Linux
# and operating systems following freedesktop.org standards.
#
# For example with "unvanquished" it will store data in
#
#   /home/<username>/.local/share/unvanquished
#
# The name is usually lowercase without space and without
# special characters.
#
# Some may prefer directory names in the form
# of “net.unvanquished.Unvanquished”, this is less common.
xdgDirName = "unvanquished"
# File base name for various files or directories written
# by the engine: screenshot base name, temporary file base name…
#
# For example with “unvanquished” it will name screenshot files
# the “unvanquished-<timestamp>.jpg way or create temporary files
# named like “/tmp/unvanquished-<random>”.
baseName = "unvanquished"
# Base name of the package the engine should look for to start the game.
# For example with “unvanquished” the engine will look for a package named
# like this:
#
#   unvanquished_<version>.dpk
#
# Packages base names are usually lowercase, don't contain white spaces
# and cannot use “_” characters except for separating the base name
# and the version string.
basePak = "unvanquished"
# List of fully qualified domain name of the master servers.
#
# Example: ["master.unvanquished.net", "master2.unvanquished.net"]
#
# Up to five master servers are supported.
masterServers = ["master.unvanquished.net", "master2.unvanquished.net"]
# URL to download missing packages when joining a server.
#
# Example: "dl.unvanquished.net/pkg"
# Or: "dl.unvanquished.net:80/pkg"
#
# It is expected to be an http server.
# The protocol is omitted.
wwwBaseUrl = "dl.unvanquished.net/pkg"
# A string used to identify against the master server.
# 
# In case of total conversion mods, this is the string of the
# game.
#
# It's usually upper case.
masterGameName = "UNVANQUISHED"
# A string used to filter games when listing servers from master
# servers.
#
# In case of total conversion mods, this is the string of the mod.
# Example: "unv" or "unvanquished" or "Unvanquished".
serverGameName = "unv"
# A string used for game server urls.
#
# For example with "unv" you can have url in the form:
#
#   unv://unvanquished.net
#
# It's lower case and usually short but you can use something longer
# similar to the base name.
uriProtocol = "unv"
