@echo off
mkdir build-32
cd build-32
cmake -C../Visual_Studio32.cmake -DBUILD_SERVER=ON -DUSE_INTERNAL_JPEG=ON -DUSE_INTERNAL_SDL=ON -DUSE_OPENAL=ON -DUSE_INTERNAL_CRYPTO=ON -DUSE_INTERNAL_SPEEX=ON -DUSE_CURSES=OFF -DUSE_GLSL_OPTIMIZER=OFF -DGAME_QVM=OFF -DBUILD_DAEMONMAP=ON -G "Visual Studio 10" ..
pause
