@echo off
mkdir build-32
cd build-32
cmake -C../Visual_Studio32.cmake -DBUILD_SERVER=OFF -DBUILD_CLIENT=OFF -DUSE_INTERNAL_JPEG=ON -DUSE_INTERNAL_SDL=ON -DUSE_OPENAL=OFF -DUSE_INTERNAL_CRYPTO=ON -DUSE_VOIP=OFF -DUSE_CURSES=OFF -DUSE_MUMBLE=OFF -DUSE_GLSL_OPTIMIZER=OFF -DGAME_QVM=OFF -G "Visual Studio 10" ..
pause