; Generated file. Do not edit.
; To update, run src/utils/scan_api.sh

code

equ memset                                -1
equ memcpy                                -2
equ memcmp                                -3
equ strncpy                               -4
equ sin                                   -5
equ cos                                   -6
equ asin                                  -7
equ tan                                   -8
equ atan                                  -9
equ atan2                                 -10
equ sqrt                                  -11
equ floor                                 -12
equ ceil                                  -13
equ exp                                   -14
equ trap_SyscallABIVersion                -256
equ trap_Print                            -257
equ trap_Error                            -258
equ trap_Log                              -259
equ trap_Milliseconds                     -260
equ trap_Cvar_Register                    -261
equ trap_Cvar_Update                      -262
equ trap_Cvar_Set                         -263
equ trap_Cvar_VariableStringBuffer        -264
equ trap_Cvar_LatchedVariableStringBuffer -265
equ trap_Cvar_VariableIntegerValue        -266
equ trap_Cvar_VariableValue               -267
equ trap_Cvar_AddFlags                    -268
equ trap_Argc                             -269
equ trap_Argv                             -270
equ trap_EscapedArgs                      -271
equ trap_LiteralArgs                      -272
equ trap_GetDemoState                     -273
equ trap_GetDemoPos                       -274
equ trap_FS_FOpenFile                     -275
equ trap_FS_Read                          -276
equ trap_FS_Write                         -277
equ trap_FS_FCloseFile                    -278
equ trap_FS_GetFileList                   -279
equ trap_FS_Delete                        -280
equ trap_FS_LoadPak                       -281
equ trap_FS_LoadAllMapMetadata            -282
equ trap_SendConsoleCommand               -283
equ trap_AddCommand                       -284
equ trap_RemoveCommand                    -285
equ trap_SendClientCommand                -286
equ trap_UpdateScreen                     -287
equ trap_CM_LoadMap                       -288
equ trap_CM_NumInlineModels               -289
equ trap_CM_InlineModel                   -290
equ trap_CM_TempBoxModel                  -291
equ trap_CM_TempCapsuleModel              -292
equ trap_CM_PointContents                 -293
equ trap_CM_TransformedPointContents      -294
equ trap_CM_BoxTrace                      -295
equ trap_CM_TransformedBoxTrace           -296
equ trap_CM_CapsuleTrace                  -297
equ trap_CM_TransformedCapsuleTrace       -298
equ trap_CM_BiSphereTrace                 -299
equ trap_CM_TransformedBiSphereTrace      -300
equ trap_CM_MarkFragments                 -301
equ trap_R_ProjectDecal                   -302
equ trap_R_ClearDecals                    -303
equ trap_S_StartSound                     -304
equ trap_S_StartSoundVControl             -304
equ trap_S_StartLocalSound                -305
equ trap_S_ClearLoopingSounds             -306
equ trap_S_ClearSounds                    -307
equ trap_S_AddLoopingSound                -308
equ trap_S_AddRealLoopingSound            -309
equ trap_S_StopLoopingSound               -310
equ trap_S_StopStreamingSound             -311
equ trap_S_UpdateEntityPosition           -312
equ trap_S_Respatialize                   -313
equ trap_S_RegisterSound                  -314
equ trap_S_StartBackgroundTrack           -315
equ trap_S_FadeBackgroundTrack            -316
equ trap_S_StartStreamingSound            -317
equ trap_R_LoadWorldMap                   -318
equ trap_R_RegisterModel                  -319
equ trap_R_RegisterSkin                   -320
equ trap_R_GetSkinModel                   -321
equ trap_R_GetShaderFromModel             -322
equ trap_R_RegisterShader                 -323
equ trap_R_RegisterFont                   -324
equ trap_R_ClearScene                     -327
equ trap_R_AddRefEntityToScene            -328
equ trap_R_AddRefLightToScene             -329
equ trap_R_AddPolyToScene                 -330
equ trap_R_AddPolysToScene                -331
equ trap_R_AddPolyBufferToScene           -332
equ trap_R_AddLightToScene                -333
equ trap_R_AddAdditiveLightToScene        -334
equ trap_GS_FS_Seek                       -335
equ trap_R_AddCoronaToScene               -336
equ trap_R_SetFog                         -337
equ trap_R_SetGlobalFog                   -338
equ trap_R_RenderScene                    -339
equ trap_R_SaveViewParms                  -340
equ trap_R_RestoreViewParms               -341
equ trap_R_SetColor                       -342
equ trap_R_SetClipRegion                  -343
equ trap_R_DrawStretchPic                 -344
equ trap_R_DrawRotatedPic                 -345
equ trap_R_DrawStretchPicGradient         -346
equ trap_R_Add2dPolys                     -347
equ trap_R_ModelBounds                    -348
equ trap_R_LerpTag                        -349
equ trap_GetGlconfig                      -350
equ trap_GetGameState                     -351
equ trap_GetClientState                   -352
equ trap_GetCurrentSnapshotNumber         -353
equ trap_GetSnapshot                      -354
equ trap_GetServerCommand                 -355
equ trap_GetCurrentCmdNumber              -356
equ trap_GetUserCmd                       -357
equ trap_SetUserCmdValue                  -358
equ trap_SetClientLerpOrigin              -359
equ trap_MemoryRemaining                  -360
equ trap_Key_IsDown                       -361
equ trap_Key_GetCatcher                   -362
equ trap_Key_SetCatcher                   -363
equ trap_Key_GetKey                       -364
equ trap_Key_GetOverstrikeMode            -365
equ trap_Key_SetOverstrikeMode            -366
equ trap_PC_AddGlobalDefine               -367
equ trap_PC_LoadSource                    -368
equ trap_PC_FreeSource                    -369
equ trap_PC_ReadToken                     -370
equ trap_PC_SourceFileAndLine             -371
equ trap_PC_UnReadToken                   -372
equ trap_S_StopBackgroundTrack            -373
equ trap_RealTime                         -374
equ trap_SnapVector                       -375
equ trap_CIN_PlayCinematic                -376
equ trap_CIN_StopCinematic                -377
equ trap_CIN_RunCinematic                 -378
equ trap_CIN_DrawCinematic                -379
equ trap_CIN_SetExtents                   -380
equ trap_R_RemapShader                    -381
equ trap_GetEntityToken                   -382
equ trap_UI_Popup                         -383
equ trap_UI_ClosePopup                    -384
equ trap_Key_GetBindingBuf                -385
equ trap_Key_SetBinding                   -386
equ trap_Parse_AddGlobalDefine            -387
equ trap_Parse_LoadSource                 -388
equ trap_Parse_FreeSource                 -389
equ trap_Parse_ReadToken                  -390
equ trap_Parse_SourceFileAndLine          -391
equ trap_Key_KeynumToStringBuf            -392
equ trap_S_FadeAllSound                   -393
equ trap_R_inPVS                          -394
equ trap_GetHunkData                      -395
equ trap_R_LoadDynamicShader              -396
equ trap_R_RenderToTexture                -397
equ trap_R_Finish                         -398
equ trap_GetDemoName                      -399
equ trap_R_LightForPoint                  -400
equ trap_R_RegisterAnimation              -401
equ trap_R_CheckSkeleton                  -402
equ trap_R_BuildSkeleton                  -403
equ trap_R_BlendSkeleton                  -404
equ trap_R_BoneIndex                      -405
equ trap_R_AnimNumFrames                  -406
equ trap_R_AnimFrameRate                  -407
equ trap_CompleteCallback                 -408
equ trap_RegisterButtonCommands           -409
equ trap_GetClipboardData                 -410
equ trap_QuoteString                      -411
equ trap_Gettext                          -412
equ trap_R_Glyph                          -413
equ trap_R_GlyphChar                      -414
equ trap_R_UnregisterFont                 -415
equ trap_Pgettext                         -416
equ trap_R_inPVVS                         -417
equ trap_notify_onTeamChange              -418
equ trap_GettextPlural                    -419
equ trap_RegisterVisTest                  -420
equ trap_AddVisTestToScene                -421
equ trap_CheckVisibility                  -422
equ trap_UnregisterVisTest                -423
equ trap_SetColorGrading                  -424
equ trap_CM_DistanceToModel               -425
equ trap_R_ScissorEnable                  -426
equ trap_R_ScissorSet                     -427
equ trap_LAN_LoadCachedServers            -428
equ trap_LAN_SaveCachedServers            -429
equ trap_LAN_AddServer                    -430
equ trap_LAN_RemoveServer                 -431
equ trap_LAN_GetPingQueueCount            -432
equ trap_LAN_ClearPing                    -433
equ trap_LAN_GetPing                      -434
equ trap_LAN_GetPingInfo                  -435
equ trap_LAN_GetServerCount               -436
equ trap_LAN_GetServerAddressString       -437
equ trap_LAN_GetServerInfo                -438
equ trap_LAN_GetServerPing                -439
equ trap_LAN_MarkServerVisible            -440
equ trap_LAN_ServerIsVisible              -441
equ trap_LAN_UpdateVisiblePings           -442
equ trap_LAN_ResetPings                   -443
equ trap_LAN_ServerStatus                 -444
equ trap_LAN_ServerIsInFavoriteList       -445
equ trap_GetNews                          -446
equ trap_LAN_CompareServers               -447
equ trap_R_GetShaderNameFromHandle        -448
equ trap_PrepareKeyUp                     -449
equ trap_R_SetAltShaderTokens             -450
equ trap_S_UpdateEntityVelocity           -451
equ trap_S_SetReverb                      -452
equ trap_S_BeginRegistration              -453
equ trap_S_EndRegistration                -454
equ trap_Rocket_Init                      -455
equ trap_Rocket_Shutdown                  -456
equ trap_Rocket_LoadDocument              -457
equ trap_Rocket_LoadCursor                -458
equ trap_Rocket_DocumentAction            -459
equ trap_Rocket_GetEvent                  -460
equ trap_Rocket_DeleteEvent               -461
equ trap_Rocket_RegisterDataSource        -462
equ trap_Rocket_DSAddRow                  -463
equ trap_Rocket_DSChangeRow               -464
equ trap_Rocket_DSRemoveRow               -465
equ trap_Rocket_DSClearTable              -466
equ trap_Rocket_SetInnerRML               -467
equ trap_Rocket_GetAttribute              -468
equ trap_Rocket_SetAttribute              -469
equ trap_Rocket_GetProperty               -470
equ trap_Rocket_SetProperty               -471
equ trap_Rocket_GetEventParameters        -472
equ trap_Rocket_RegisterDataFormatter     -473
equ trap_Rocket_DataFormatterRawData      -474
equ trap_Rocket_DataFormatterFormattedData -475
equ trap_Rocket_RegisterElement           -476
equ trap_Rocket_SetElementDimensions      -477
equ trap_Rocket_GetElementTag             -478
equ trap_Rocket_GetElementAbsoluteOffset  -479
equ trap_Rocket_QuakeToRML                -480
equ trap_Rocket_SetClass                  -481
equ trap_Rocket_InitializeHuds            -482
equ trap_Rocket_LoadUnit                  -483
equ trap_Rocket_AddUnitToHud              -484
equ trap_Rocket_ShowHud                   -485
equ trap_Rocket_ClearHud                  -486
equ trap_Rocket_AddTextElement            -487
equ trap_Rocket_ClearText                 -488
equ trap_Rocket_RegisterProperty          -489
equ trap_Rocket_ShowScoreboard            -490
equ trap_Rocket_SetDataSelectIndex        -491
equ trap_Rocket_LoadFont                  -492
