; Generated file. Do not edit.
; To update, run src/utils/scan_api.sh

code

equ memset                                -1
equ memcpy                                -2
equ memcmp                                -3
equ strncpy                               -4
equ sin                                   -5
equ cos                                   -6
equ asin                                  -7
equ tan                                   -8
equ atan                                  -9
equ atan2                                 -10
equ sqrt                                  -11
equ floor                                 -12
equ ceil                                  -13
equ exp                                   -14
equ trap_SyscallABIVersion                -256
equ trap_Print                            -257
equ trap_Error                            -258
equ trap_Log                              -259
equ trap_Milliseconds                     -260
equ trap_Cvar_Register                    -261
equ trap_Cvar_Update                      -262
equ trap_Cvar_Set                         -263
equ trap_Cvar_VariableStringBuffer        -264
equ trap_Cvar_LatchedVariableStringBuffer -265
equ trap_Cvar_VariableIntegerValue        -266
equ trap_Cvar_VariableValue               -267
equ trap_Argc                             -268
equ trap_Argv                             -269
equ trap_EscapedArgs                      -270
equ trap_LiteralArgs                      -271
equ trap_GetDemoState                     -272
equ trap_GetDemoPos                       -273
equ trap_FS_FOpenFile                     -274
equ trap_FS_Read                          -275
equ trap_FS_Write                         -276
equ trap_FS_FCloseFile                    -277
equ trap_FS_GetFileList                   -278
equ trap_FS_Delete                        -279
equ trap_SendConsoleCommand               -280
equ trap_AddCommand                       -281
equ trap_RemoveCommand                    -282
equ trap_SendClientCommand                -283
equ trap_UpdateScreen                     -284
equ trap_CM_LoadMap                       -285
equ trap_CM_NumInlineModels               -286
equ trap_CM_InlineModel                   -287
equ trap_CM_TempBoxModel                  -288
equ trap_CM_TempCapsuleModel              -289
equ trap_CM_PointContents                 -290
equ trap_CM_TransformedPointContents      -291
equ trap_CM_BoxTrace                      -292
equ trap_CM_TransformedBoxTrace           -293
equ trap_CM_CapsuleTrace                  -294
equ trap_CM_TransformedCapsuleTrace       -295
equ trap_CM_BiSphereTrace                 -296
equ trap_CM_TransformedBiSphereTrace      -297
equ trap_CM_MarkFragments                 -298
equ trap_R_ProjectDecal                   -299
equ trap_R_ClearDecals                    -300
equ trap_S_StartSound                     -301
equ trap_S_StartSoundVControl             -301
equ trap_S_StartLocalSound                -302
equ trap_S_ClearLoopingSounds             -303
equ trap_S_ClearSounds                    -304
equ trap_S_AddLoopingSound                -305
equ trap_S_AddRealLoopingSound            -306
equ trap_S_StopLoopingSound               -307
equ trap_S_StopStreamingSound             -308
equ trap_S_UpdateEntityPosition           -309
equ trap_S_Respatialize                   -310
equ trap_S_RegisterSound                  -311
equ trap_S_StartBackgroundTrack           -312
equ trap_S_FadeBackgroundTrack            -313
equ trap_S_StartStreamingSound            -314
equ trap_R_LoadWorldMap                   -315
equ trap_R_RegisterModel                  -316
equ trap_R_RegisterSkin                   -317
equ trap_R_GetSkinModel                   -318
equ trap_R_GetShaderFromModel             -319
equ trap_R_RegisterShader                 -320
equ trap_R_RegisterFont                   -321
equ trap_R_ClearScene                     -324
equ trap_R_AddRefEntityToScene            -325
equ trap_R_AddRefLightToScene             -326
equ trap_R_AddPolyToScene                 -327
equ trap_R_AddPolysToScene                -328
equ trap_R_AddPolyBufferToScene           -329
equ trap_R_AddLightToScene                -330
equ trap_R_AddAdditiveLightToScene        -331
equ trap_GS_FS_Seek                       -332
equ trap_R_AddCoronaToScene               -333
equ trap_R_SetFog                         -334
equ trap_R_SetGlobalFog                   -335
equ trap_R_RenderScene                    -336
equ trap_R_SaveViewParms                  -337
equ trap_R_RestoreViewParms               -338
equ trap_R_SetColor                       -339
equ trap_R_SetClipRegion                  -340
equ trap_R_DrawStretchPic                 -341
equ trap_R_DrawRotatedPic                 -342
equ trap_R_DrawStretchPicGradient         -343
equ trap_R_Add2dPolys                     -344
equ trap_R_ModelBounds                    -345
equ trap_R_LerpTag                        -346
equ trap_GetGlconfig                      -347
equ trap_GetGameState                     -348
equ trap_GetClientState                   -349
equ trap_GetCurrentSnapshotNumber         -350
equ trap_GetSnapshot                      -351
equ trap_GetServerCommand                 -352
equ trap_GetCurrentCmdNumber              -353
equ trap_GetUserCmd                       -354
equ trap_SetUserCmdValue                  -355
equ trap_SetClientLerpOrigin              -356
equ trap_MemoryRemaining                  -357
equ trap_Key_IsDown                       -358
equ trap_Key_GetCatcher                   -359
equ trap_Key_SetCatcher                   -360
equ trap_Key_GetKey                       -361
equ trap_Key_GetOverstrikeMode            -362
equ trap_Key_SetOverstrikeMode            -363
equ trap_PC_AddGlobalDefine               -364
equ trap_PC_LoadSource                    -365
equ trap_PC_FreeSource                    -366
equ trap_PC_ReadToken                     -367
equ trap_PC_SourceFileAndLine             -368
equ trap_PC_UnReadToken                   -369
equ trap_S_StopBackgroundTrack            -370
equ trap_RealTime                         -371
equ trap_SnapVector                       -372
equ trap_CIN_PlayCinematic                -373
equ trap_CIN_StopCinematic                -374
equ trap_CIN_RunCinematic                 -375
equ trap_CIN_DrawCinematic                -376
equ trap_CIN_SetExtents                   -377
equ trap_R_RemapShader                    -378
equ trap_GetEntityToken                   -379
equ trap_UI_Popup                         -380
equ trap_UI_ClosePopup                    -381
equ trap_Key_GetBindingBuf                -382
equ trap_Key_SetBinding                   -383
equ trap_Parse_AddGlobalDefine            -384
equ trap_Parse_LoadSource                 -385
equ trap_Parse_FreeSource                 -386
equ trap_Parse_ReadToken                  -387
equ trap_Parse_SourceFileAndLine          -388
equ trap_Key_KeynumToStringBuf            -389
equ trap_S_FadeAllSound                   -390
equ trap_R_inPVS                          -391
equ trap_GetHunkData                      -392
equ trap_R_LoadDynamicShader              -393
equ trap_R_RenderToTexture                -394
equ trap_R_Finish                         -395
equ trap_GetDemoName                      -396
equ trap_R_LightForPoint                  -397
equ trap_R_RegisterAnimation              -398
equ trap_R_CheckSkeleton                  -399
equ trap_R_BuildSkeleton                  -400
equ trap_R_BlendSkeleton                  -401
equ trap_R_BoneIndex                      -402
equ trap_R_AnimNumFrames                  -403
equ trap_R_AnimFrameRate                  -404
equ trap_CompleteCallback                 -405
equ trap_RegisterButtonCommands           -406
equ trap_GetClipboardData                 -407
equ trap_QuoteString                      -408
equ trap_Gettext                          -409
equ trap_R_Glyph                          -410
equ trap_R_GlyphChar                      -411
equ trap_R_UnregisterFont                 -412
equ trap_Pgettext                         -413
equ trap_R_inPVVS                         -414
equ trap_notify_onTeamChange              -415
equ trap_GettextPlural                    -416
equ trap_RegisterVisTest                  -417
equ trap_AddVisTestToScene                -418
equ trap_CheckVisibility                  -419
equ trap_UnregisterVisTest                -420
equ trap_SetColorGrading                  -421
equ trap_CM_DistanceToModel               -422
equ trap_R_ScissorEnable                  -423
equ trap_R_ScissorSet                     -424
equ trap_LAN_LoadCachedServers            -425
equ trap_LAN_SaveCachedServers            -426
equ trap_LAN_AddServer                    -427
equ trap_LAN_RemoveServer                 -428
equ trap_LAN_GetPingQueueCount            -429
equ trap_LAN_ClearPing                    -430
equ trap_LAN_GetPing                      -431
equ trap_LAN_GetPingInfo                  -432
equ trap_LAN_GetServerCount               -433
equ trap_LAN_GetServerAddressString       -434
equ trap_LAN_GetServerInfo                -435
equ trap_LAN_GetServerPing                -436
equ trap_LAN_MarkServerVisible            -437
equ trap_LAN_ServerIsVisible              -438
equ trap_LAN_UpdateVisiblePings           -439
equ trap_LAN_ResetPings                   -440
equ trap_LAN_ServerStatus                 -441
equ trap_LAN_ServerIsInFavoriteList       -442
equ trap_GetNews                          -443
equ trap_LAN_CompareServers               -444
equ trap_R_GetShaderNameFromHandle        -445
equ trap_PrepareKeyUp                     -446
equ trap_R_SetAltShaderTokens             -447
equ trap_S_UpdateEntityVelocity           -448
equ trap_S_SetReverb                      -449
equ trap_S_BeginRegistration              -450
equ trap_S_EndRegistration                -451
equ trap_Rocket_Init                      -452
equ trap_Rocket_Shutdown                  -453
equ trap_Rocket_LoadDocument              -454
equ trap_Rocket_LoadCursor                -455
equ trap_Rocket_DocumentAction            -456
equ trap_Rocket_GetEvent                  -457
equ trap_Rocket_DeleteEvent               -458
equ trap_Rocket_RegisterDataSource        -459
equ trap_Rocket_DSAddRow                  -460
equ trap_Rocket_DSChangeRow               -461
equ trap_Rocket_DSRemoveRow               -462
equ trap_Rocket_DSClearTable              -463
equ trap_Rocket_SetInnerRML               -464
equ trap_Rocket_GetAttribute              -465
equ trap_Rocket_SetAttribute              -466
equ trap_Rocket_GetProperty               -467
equ trap_Rocket_SetProperty               -468
equ trap_Rocket_GetEventParameters        -469
equ trap_Rocket_RegisterDataFormatter     -470
equ trap_Rocket_DataFormatterRawData      -471
equ trap_Rocket_DataFormatterFormattedData -472
equ trap_Rocket_RegisterElement           -473
equ trap_Rocket_SetElementDimensions      -474
equ trap_Rocket_GetElementTag             -475
equ trap_Rocket_KeyToQuake                -476
equ trap_Rocket_GetElementAbsoluteOffset  -477
equ trap_Rocket_QuakeToRML                -478
equ trap_Rocket_SetClass                  -479
equ trap_Rocket_InitializeHuds            -480
equ trap_Rocket_LoadUnit                  -481
equ trap_Rocket_AddUnitToHud              -482
equ trap_Rocket_ShowHud                   -483
equ trap_Rocket_ClearHud                  -484
equ trap_Rocket_AddTextElement            -485
equ trap_Rocket_ClearText                 -486
equ trap_Rocket_RegisterProperty          -487
equ trap_Rocket_ShowScoreboard            -488
equ trap_Rocket_SetDataSelectIndex        -489
