; Generated file. Do not edit.
; To update, run src/utils/scan_api.sh

code

equ memset                                -1
equ memcpy                                -2
equ memcmp                                -3
equ strncpy                               -4
equ sin                                   -5
equ cos                                   -6
equ asin                                  -7
equ tan                                   -8
equ atan                                  -9
equ atan2                                 -10
equ sqrt                                  -11
equ floor                                 -12
equ ceil                                  -13
equ exp                                   -14
equ trap_SyscallABIVersion                -256
equ trap_Print                            -257
equ trap_Error                            -258
equ trap_Log                              -259
equ trap_Milliseconds                     -260
equ trap_Cvar_Register                    -261
equ trap_Cvar_Update                      -262
equ trap_Cvar_Set                         -263
equ trap_Cvar_VariableStringBuffer        -264
equ trap_Cvar_LatchedVariableStringBuffer -265
equ trap_Cvar_VariableIntegerValue        -266
equ trap_Cvar_VariableValue               -267
equ trap_Argc                             -268
equ trap_Argv                             -269
equ trap_EscapedArgs                      -270
equ trap_LiteralArgs                      -271
equ trap_GetDemoState                     -272
equ trap_GetDemoPos                       -273
equ trap_FS_FOpenFile                     -274
equ trap_FS_Read                          -275
equ trap_FS_Write                         -276
equ trap_FS_FCloseFile                    -277
equ trap_FS_GetFileList                   -278
equ trap_FS_Delete                        -279
equ trap_FS_LoadPak                       -280
equ trap_SendConsoleCommand               -281
equ trap_AddCommand                       -282
equ trap_RemoveCommand                    -283
equ trap_SendClientCommand                -284
equ trap_UpdateScreen                     -285
equ trap_CM_LoadMap                       -286
equ trap_CM_NumInlineModels               -287
equ trap_CM_InlineModel                   -288
equ trap_CM_TempBoxModel                  -289
equ trap_CM_TempCapsuleModel              -290
equ trap_CM_PointContents                 -291
equ trap_CM_TransformedPointContents      -292
equ trap_CM_BoxTrace                      -293
equ trap_CM_TransformedBoxTrace           -294
equ trap_CM_CapsuleTrace                  -295
equ trap_CM_TransformedCapsuleTrace       -296
equ trap_CM_BiSphereTrace                 -297
equ trap_CM_TransformedBiSphereTrace      -298
equ trap_CM_MarkFragments                 -299
equ trap_R_ProjectDecal                   -300
equ trap_R_ClearDecals                    -301
equ trap_S_StartSound                     -302
equ trap_S_StartSoundVControl             -302
equ trap_S_StartLocalSound                -303
equ trap_S_ClearLoopingSounds             -304
equ trap_S_ClearSounds                    -305
equ trap_S_AddLoopingSound                -306
equ trap_S_AddRealLoopingSound            -307
equ trap_S_StopLoopingSound               -308
equ trap_S_StopStreamingSound             -309
equ trap_S_UpdateEntityPosition           -310
equ trap_S_Respatialize                   -311
equ trap_S_RegisterSound                  -312
equ trap_S_StartBackgroundTrack           -313
equ trap_S_FadeBackgroundTrack            -314
equ trap_S_StartStreamingSound            -315
equ trap_R_LoadWorldMap                   -316
equ trap_R_RegisterModel                  -317
equ trap_R_RegisterSkin                   -318
equ trap_R_GetSkinModel                   -319
equ trap_R_GetShaderFromModel             -320
equ trap_R_RegisterShader                 -321
equ trap_R_RegisterFont                   -322
equ trap_R_ClearScene                     -325
equ trap_R_AddRefEntityToScene            -326
equ trap_R_AddRefLightToScene             -327
equ trap_R_AddPolyToScene                 -328
equ trap_R_AddPolysToScene                -329
equ trap_R_AddPolyBufferToScene           -330
equ trap_R_AddLightToScene                -331
equ trap_R_AddAdditiveLightToScene        -332
equ trap_GS_FS_Seek                       -333
equ trap_R_AddCoronaToScene               -334
equ trap_R_SetFog                         -335
equ trap_R_SetGlobalFog                   -336
equ trap_R_RenderScene                    -337
equ trap_R_SaveViewParms                  -338
equ trap_R_RestoreViewParms               -339
equ trap_R_SetColor                       -340
equ trap_R_SetClipRegion                  -341
equ trap_R_DrawStretchPic                 -342
equ trap_R_DrawRotatedPic                 -343
equ trap_R_DrawStretchPicGradient         -344
equ trap_R_Add2dPolys                     -345
equ trap_R_ModelBounds                    -346
equ trap_R_LerpTag                        -347
equ trap_GetGlconfig                      -348
equ trap_GetGameState                     -349
equ trap_GetClientState                   -350
equ trap_GetCurrentSnapshotNumber         -351
equ trap_GetSnapshot                      -352
equ trap_GetServerCommand                 -353
equ trap_GetCurrentCmdNumber              -354
equ trap_GetUserCmd                       -355
equ trap_SetUserCmdValue                  -356
equ trap_SetClientLerpOrigin              -357
equ trap_MemoryRemaining                  -358
equ trap_Key_IsDown                       -359
equ trap_Key_GetCatcher                   -360
equ trap_Key_SetCatcher                   -361
equ trap_Key_GetKey                       -362
equ trap_Key_GetOverstrikeMode            -363
equ trap_Key_SetOverstrikeMode            -364
equ trap_PC_AddGlobalDefine               -365
equ trap_PC_LoadSource                    -366
equ trap_PC_FreeSource                    -367
equ trap_PC_ReadToken                     -368
equ trap_PC_SourceFileAndLine             -369
equ trap_PC_UnReadToken                   -370
equ trap_S_StopBackgroundTrack            -371
equ trap_RealTime                         -372
equ trap_SnapVector                       -373
equ trap_CIN_PlayCinematic                -374
equ trap_CIN_StopCinematic                -375
equ trap_CIN_RunCinematic                 -376
equ trap_CIN_DrawCinematic                -377
equ trap_CIN_SetExtents                   -378
equ trap_R_RemapShader                    -379
equ trap_GetEntityToken                   -380
equ trap_UI_Popup                         -381
equ trap_UI_ClosePopup                    -382
equ trap_Key_GetBindingBuf                -383
equ trap_Key_SetBinding                   -384
equ trap_Parse_AddGlobalDefine            -385
equ trap_Parse_LoadSource                 -386
equ trap_Parse_FreeSource                 -387
equ trap_Parse_ReadToken                  -388
equ trap_Parse_SourceFileAndLine          -389
equ trap_Key_KeynumToStringBuf            -390
equ trap_S_FadeAllSound                   -391
equ trap_R_inPVS                          -392
equ trap_GetHunkData                      -393
equ trap_R_LoadDynamicShader              -394
equ trap_R_RenderToTexture                -395
equ trap_R_Finish                         -396
equ trap_GetDemoName                      -397
equ trap_R_LightForPoint                  -398
equ trap_R_RegisterAnimation              -399
equ trap_R_CheckSkeleton                  -400
equ trap_R_BuildSkeleton                  -401
equ trap_R_BlendSkeleton                  -402
equ trap_R_BoneIndex                      -403
equ trap_R_AnimNumFrames                  -404
equ trap_R_AnimFrameRate                  -405
equ trap_CompleteCallback                 -406
equ trap_RegisterButtonCommands           -407
equ trap_GetClipboardData                 -408
equ trap_QuoteString                      -409
equ trap_Gettext                          -410
equ trap_R_Glyph                          -411
equ trap_R_GlyphChar                      -412
equ trap_R_UnregisterFont                 -413
equ trap_Pgettext                         -414
equ trap_R_inPVVS                         -415
equ trap_notify_onTeamChange              -416
equ trap_GettextPlural                    -417
equ trap_RegisterVisTest                  -418
equ trap_AddVisTestToScene                -419
equ trap_CheckVisibility                  -420
equ trap_UnregisterVisTest                -421
equ trap_SetColorGrading                  -422
equ trap_CM_DistanceToModel               -423
equ trap_R_ScissorEnable                  -424
equ trap_R_ScissorSet                     -425
equ trap_LAN_LoadCachedServers            -426
equ trap_LAN_SaveCachedServers            -427
equ trap_LAN_AddServer                    -428
equ trap_LAN_RemoveServer                 -429
equ trap_LAN_GetPingQueueCount            -430
equ trap_LAN_ClearPing                    -431
equ trap_LAN_GetPing                      -432
equ trap_LAN_GetPingInfo                  -433
equ trap_LAN_GetServerCount               -434
equ trap_LAN_GetServerAddressString       -435
equ trap_LAN_GetServerInfo                -436
equ trap_LAN_GetServerPing                -437
equ trap_LAN_MarkServerVisible            -438
equ trap_LAN_ServerIsVisible              -439
equ trap_LAN_UpdateVisiblePings           -440
equ trap_LAN_ResetPings                   -441
equ trap_LAN_ServerStatus                 -442
equ trap_LAN_ServerIsInFavoriteList       -443
equ trap_GetNews                          -444
equ trap_LAN_CompareServers               -445
equ trap_R_GetShaderNameFromHandle        -446
equ trap_PrepareKeyUp                     -447
equ trap_R_SetAltShaderTokens             -448
equ trap_S_UpdateEntityVelocity           -449
equ trap_S_SetReverb                      -450
equ trap_S_BeginRegistration              -451
equ trap_S_EndRegistration                -452
equ trap_Rocket_Init                      -453
equ trap_Rocket_Shutdown                  -454
equ trap_Rocket_LoadDocument              -455
equ trap_Rocket_LoadCursor                -456
equ trap_Rocket_DocumentAction            -457
equ trap_Rocket_GetEvent                  -458
equ trap_Rocket_DeleteEvent               -459
equ trap_Rocket_RegisterDataSource        -460
equ trap_Rocket_DSAddRow                  -461
equ trap_Rocket_DSChangeRow               -462
equ trap_Rocket_DSRemoveRow               -463
equ trap_Rocket_DSClearTable              -464
equ trap_Rocket_SetInnerRML               -465
equ trap_Rocket_GetAttribute              -466
equ trap_Rocket_SetAttribute              -467
equ trap_Rocket_GetProperty               -468
equ trap_Rocket_SetProperty               -469
equ trap_Rocket_GetEventParameters        -470
equ trap_Rocket_RegisterDataFormatter     -471
equ trap_Rocket_DataFormatterRawData      -472
equ trap_Rocket_DataFormatterFormattedData -473
equ trap_Rocket_RegisterElement           -474
equ trap_Rocket_SetElementDimensions      -475
equ trap_Rocket_GetElementTag             -476
equ trap_Rocket_GetElementAbsoluteOffset  -477
equ trap_Rocket_QuakeToRML                -478
equ trap_Rocket_SetClass                  -479
equ trap_Rocket_InitializeHuds            -480
equ trap_Rocket_LoadUnit                  -481
equ trap_Rocket_AddUnitToHud              -482
equ trap_Rocket_ShowHud                   -483
equ trap_Rocket_ClearHud                  -484
equ trap_Rocket_AddTextElement            -485
equ trap_Rocket_ClearText                 -486
equ trap_Rocket_RegisterProperty          -487
equ trap_Rocket_ShowScoreboard            -488
equ trap_Rocket_SetDataSelectIndex        -489
