#!/bin/sh

if [[ "$GEN" == "" ]];then
	echo "Usage: GEN=<path_to_generator> $0"
	exit -1
fi

# base directory for output files
base_dir="$(pwd)"

# entitiy definition file (input file)
definition="${base_dir}/components.yaml"

# directory for component implementation files (not autogenerated)
component_sub="components"
component_dir="${base_dir}/${component_sub}/"

# directory for component implementation file skeletons (autogenerated)
skeleton_dir="${component_dir}/skel/"

# plumbing code (autogenerated)
implementation="${base_dir}/Components.cpp"
declaration="${base_dir}/Components.h"
entities="${base_dir}/ComponentsEntities.h"
include_helper="${component_dir}/ComponentImplementationInclude.h"

cd $(dirname ${GEN}) || exit -2

${GEN} -s "${skeleton_dir}" -i "${implementation}" -d "${declaration}" -e "${entities}" -l "${include_helper}" "${definition}"

