code

equ	trap_Error                              -1
equ trap_Error                              -2
equ trap_Milliseconds                       -3
equ trap_Cvar_Register                      -4
equ trap_Cvar_Update                        -5
equ trap_Cvar_Set                           -6
equ trap_Cvar_VariableValue                 -7
equ trap_Cvar_VariableStringBuffer          -8
equ trap_Cvar_LatchedVariableStringBuffer   -9
equ trap_Cvar_SetValue                      -10
equ trap_Cvar_CopyValue_i                   -11
equ trap_Cvar_Reset                         -12
equ trap_Cvar_Create                        -13
equ trap_Cvar_InfoStringBuffer              -14
equ trap_Argc                               -15
equ trap_Argv                               -16
equ trap_Cmd_ExecuteText                    -17
equ trap_AddCommand                         -18
equ trap_FS_FOpenFile                       -19
equ trap_FS_Read                            -20
equ trap_FS_Write                           -21
equ trap_FS_FCloseFile                      -22
equ trap_FS_GetFileList                     -23
equ trap_FS_Delete                          -24
equ trap_R_RegisterModel                    -25
equ trap_R_RegisterSkin                     -26
equ trap_R_RegisterFont                     -27
equ trap_R_RegisterShaderNoMip              -28
equ trap_R_ClearScene                       -29
equ trap_R_AddRefEntityToScene              -30
equ trap_R_AddPolyToScene                   -31
equ trap_R_AddLightToScene                  -32
equ trap_R_AddCoronaToScene                 -33
equ trap_R_RenderScene                      -34
equ trap_R_SetColor                         -35
equ trap_R_Add2dPolys                       -36
equ trap_R_DrawStretchPic                   -37
equ trap_R_DrawRotatedPic                   -38
equ trap_R_ModelBounds                      -39
equ trap_UpdateScreen                       -40
equ trap_CM_LerpTag                         -41
equ trap_S_StartLocalSound                  -42
equ trap_S_RegisterSound                    -43
equ trap_S_FadeBackgroundTrack              -44
equ trap_S_FadeAllSound                     -45
equ trap_Key_KeynumToStringBuf              -46
equ trap_Key_GetBindingBuf                  -47
equ trap_Key_KeysForBinding                 -48
equ trap_Key_SetBinding                     -49
equ trap_Key_IsDown                         -50
equ trap_Key_GetOverstrikeMode              -51
equ trap_Key_SetOverstrikeMode              -52
equ trap_Key_ClearStates                    -53
equ trap_Key_GetCatcher                     -54
equ trap_Key_SetCatcher                     -55
equ trap_GetClipboardData                   -56
equ trap_GetClientState                     -57
equ trap_GetGlconfig                        -58
equ trap_GetConfigString                    -59
equ trap_LAN_GetLocalServerCount            -60
equ trap_LAN_GetLocalServerAddressString    -61
equ trap_LAN_GetGlobalServerCount           -62
equ trap_LAN_GetGlobalServerAddressString   -63
equ trap_LAN_GetPingQueueCount              -64
equ trap_LAN_ClearPing                      -65
equ trap_LAN_GetPing                        -66
equ trap_LAN_GetPingInfo                    -67
equ trap_LAN_UpdateVisiblePings             -68
equ trap_LAN_GetServerCount                 -69
equ trap_LAN_CompareServers                 -70
equ trap_LAN_GetServerAddressString         -71
equ trap_LAN_GetServerInfo                  -72
equ trap_LAN_AddServer                      -73
equ trap_LAN_RemoveServer                   -74
equ trap_LAN_GetServerPing                  -75
equ trap_LAN_ServerIsVisible                -76
equ trap_LAN_ServerStatus                   -77
equ trap_LAN_ServerIsInFavoriteList         -78
equ trap_LAN_SaveCachedServers              -79
equ trap_LAN_LoadCachedServers              -80
equ trap_LAN_MarkServerVisible              -81
equ trap_SetPbClStatus                      -82
equ trap_SetPbSvStatus                      -83
equ trap_LAN_ResetPings                     -84
equ trap_MemoryRemaining                    -85
equ trap_GetCDKey                           -86
equ trap_SetCDKey                           -87
equ trap_PC_AddGlobalDefine                 -88
equ trap_PC_RemoveAllGlobalDefines          -89
equ trap_PC_LoadSource                      -90
equ trap_PC_FreeSource                      -91
equ trap_PC_ReadToken                       -92
equ trap_PC_SourceFileAndLine               -93
equ trap_PC_UnReadToken                     -94
equ trap_S_StopBackgroundTrack              -95
equ trap_S_StartBackgroundTrack             -96
equ trap_RealTime                           -97
equ trap_CIN_PlayCinematic                  -98
equ trap_CIN_StopCinematic                  -99
equ trap_CIN_RunCinematic                   -100
equ trap_CIN_DrawCinematic                  -101
equ trap_CIN_SetExtents                     -102
equ trap_R_RemapShader                      -103
equ trap_VerifyCDKey                        -104
equ trap_GetLimboString                     -105
equ trap_TranslateString                    -106
equ trap_CheckAutoUpdate                    -107
equ trap_GetAutoUpdate                      -108
equ trap_openURL                            -109
equ trap_GetHunkData                        -110

equ	memset						            -201
equ	memcpy						            -202
equ	strncpy						            -203
equ	sin							            -204
equ	cos							            -205
equ	atan2						            -206
equ	sqrt						            -207
equ floor						            -208
equ	ceil						            -209
