#ifndef ACIDBOMB_COMPONENT_H_
#define ACIDBOMB_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class AcidbombComponent: public AcidbombComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the AcidbombComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_TeamComponent A TeamComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		AcidbombComponent(Entity& entity, TeamComponent& r_TeamComponent);

		/**
		 * @brief Handle the Die message.
		 * @param killer
		 * @param meansOfDeath
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleDie(gentity_t* killer, meansOfDeath_t meansOfDeath);

		// ///////////////////// //

		void Explode();

	private:

};

#endif // ACIDBOMB_COMPONENT_H_
