#ifndef CORRODIBLE_COMPONENT_H_
#define CORRODIBLE_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class CorrodibleComponent: public CorrodibleComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the CorrodibleComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_ThinkingComponent A ThinkingComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		CorrodibleComponent(Entity& entity, ThinkingComponent& r_ThinkingComponent);

		/**
		 * @brief Handle the PrepareNetCode message.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandlePrepareNetCode();

		/**
		 * @brief Handle the Corrode message.
		 * @param corrode
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleCorrode(gentity_t* actor, bool corrode);

		/**
		 * @brief Handle the Heal message.
		 * @param amount
		 * @param source
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleHeal(float amount, gentity_t* source);

		// ///////////////////// //

	private:
		void Damage(int timeDelta);

		bool corrode_;
		int corrodeEndTime_;
		GentityRef actor_;

};

#endif // CORRODIBLE_COMPONENT_H_
