#ifndef EGG_COMPONENT_H_
#define EGG_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class EggComponent: public EggComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the EggComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_AlienBuildableComponent A AlienBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		EggComponent(Entity& entity, AlienBuildableComponent& r_AlienBuildableComponent);

		// ///////////////////// //

	private:

};

#endif // EGG_COMPONENT_H_
