#ifndef MGTURRET_COMPONENT_H_
#define MGTURRET_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class MGTurretComponent: public MGTurretComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the MGTurretComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_HumanBuildableComponent A HumanBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		MGTurretComponent(Entity& entity, HumanBuildableComponent& r_HumanBuildableComponent);

		// ///////////////////// //

	private:

};

#endif // MGTURRET_COMPONENT_H_
