#ifndef OVERMIND_COMPONENT_H_
#define OVERMIND_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class OvermindComponent: public OvermindComponentBase {
	public:
		const static float ATTACK_RANGE;
		const static float ATTACK_DAMAGE; /**< In pure damage per second. */

		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the OvermindComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_AlienBuildableComponent A AlienBuildableComponent instance that this component depends on.
		 * @param r_MainBuildableComponent A MainBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		OvermindComponent(Entity& entity, AlienBuildableComponent& r_AlienBuildableComponent, MainBuildableComponent& r_MainBuildableComponent);

		/**
		 * @brief Handle the PrepareNetCode message.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandlePrepareNetCode();

		/**
		 * @brief Handle the FinishConstruction message.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleFinishConstruction();

		// ///////////////////// //

	private:
		GentityRef storedTarget;

		void Think(int timeDelta);

		Entity* FindTarget();
		bool CompareTargets(Entity& a, Entity& b) const;
};

#endif // OVERMIND_COMPONENT_H_
