#ifndef REACTOR_COMPONENT_H_
#define REACTOR_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class ReactorComponent: public ReactorComponentBase {
	public:
		const static float ATTACK_RANGE;
		const static float ATTACK_DAMAGE; /** In maximum damage per second. */

		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the ReactorComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_HumanBuildableComponent A HumanBuildableComponent instance that this component depends on.
		 * @param r_MainBuildableComponent A MainBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		ReactorComponent(Entity& entity, HumanBuildableComponent& r_HumanBuildableComponent, MainBuildableComponent& r_MainBuildableComponent);

		// ///////////////////// //

	private:

		void Think(int timeDelta);

		void CreateTeslaTrail(Entity& target);

};

#endif // REACTOR_COMPONENT_H_
