#ifndef SPECTATORCLASS_COMPONENT_H_
#define SPECTATORCLASS_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class SpectatorClassComponent: public SpectatorClassComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the SpectatorClassComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_ClientComponent A ClientComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		SpectatorClassComponent(Entity& entity, ClientComponent& r_ClientComponent);

		/**
		 * @brief Handle the PrepareNetCode message.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandlePrepareNetCode();

		// ///////////////////// //

	private:

};

#endif // SPECTATORCLASS_COMPONENT_H_
