#ifndef SPECTATOR_COMPONENT_H_
#define SPECTATOR_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class SpectatorComponent: public SpectatorComponentBase {
public:
	// ///////////////////// //
	// Autogenerated Members //
	// ///////////////////// //

	/**
	 * @brief Default constructor of the SpectatorComponent.
	 * @param entity The entity that owns the component instance.
	 * @param r_ClientComponent A ClientComponent instance that this component depends on.
	 * @param r_HealthComponent A HealthComponent instance that this component depends on.
	 * @note This method is an interface for autogenerated code, do not modify its signature.
	 */
	SpectatorComponent(Entity& entity, ClientComponent& r_ClientComponent, HealthComponent& r_HealthComponent);

	/**
	 * @brief Handle the PrepareNetCode message.
	 * @note This method is an interface for autogenerated code, do not modify its signature.
	 */
	void HandlePrepareNetCode();

	// ///////////////////// //

private:

};

#endif // SPECTATOR_COMPONENT_H_
