#ifndef TEAM_COMPONENT_H_
#define TEAM_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class TeamComponent: public TeamComponentBase {
	public:
		// TODO: Move the team_t enum here.
		using team_t = ::team_t;

		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the TeamComponent.
		 * @param entity The entity that owns the component instance.
		 * @param team An initialization parameter.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		TeamComponent(Entity& entity, team_t team);

		// ///////////////////// //

		team_t Team() const { return team; }

		bool operator==(const TeamComponent& other) const {
			return Team() == other.Team();
		}

		bool operator!=(const TeamComponent& other) const {
			return !(*this == other);
		}

	private:

};

#endif // TEAM_COMPONENT_H_
