#ifndef TRAPPER_COMPONENT_H_
#define TRAPPER_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class TrapperComponent: public TrapperComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the TrapperComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_AlienBuildableComponent A AlienBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		TrapperComponent(Entity& entity, AlienBuildableComponent& r_AlienBuildableComponent);

		// ///////////////////// //

	private:

};

#endif // TRAPPER_COMPONENT_H_
