#ifndef ZAP_COMPONENT_H_
#define ZAP_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class ZapComponent: public ZapComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the ZapComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_ClientComponent A ClientComponent instance that this component depends on.
		 * @param r_ThinkingComponent A ThinkingComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		ZapComponent(Entity& entity, ClientComponent& r_ClientComponent, ThinkingComponent& r_ThinkingComponent);

		/**
		 * @brief Handle the ZapTarget message.
		 * @param target
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleZapTarget(Entity& target);

		/**
		 * @brief Handle the ClearZap message.
		 * @param player
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleClearZap(Entity& player);

		// ///////////////////// //

	private:
		void UpdateZap(int timeDelta);
		void UpdateZapTarget(int timeDelta);

		zap_t zap;
};

#endif // ZAP_COMPONENT_H_
