#ifndef ARMOR_COMPONENT_H_
#define ARMOR_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class ArmorComponent: public ArmorComponentBase {

	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the ArmorComponent.
		 * @param entity The entity that owns the component instance.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		ArmorComponent(Entity& entity);

		// /////////////////// //
		// Handwritten Members //
		// /////////////////// //

		float DamageModifier(Util::optional<Vec3> location, int damageFlags);

	private:
		// /////////////////// //
		// Handwritten Members //
		// /////////////////// //

};

#endif // ARMOR_COMPONENT_H_

