#ifndef ARMOURY_COMPONENT_H_
#define ARMOURY_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class ArmouryComponent: public ArmouryComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the ArmouryComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_HumanBuildableComponent A HumanBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		ArmouryComponent(Entity& entity, HumanBuildableComponent& r_HumanBuildableComponent);

		// ///////////////////// //

	private:

};

#endif // ARMOURY_COMPONENT_H_
