#ifndef BOOSTER_COMPONENT_H_
#define BOOSTER_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class BoosterComponent: public BoosterComponentBase {
	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the BoosterComponent.
		 * @param entity The entity that owns the component instance.
		 * @param r_AlienBuildableComponent A AlienBuildableComponent instance that this component depends on.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		BoosterComponent(Entity& entity, AlienBuildableComponent& r_AlienBuildableComponent);

		// ///////////////////// //

	private:

};

#endif // BOOSTER_COMPONENT_H_
