#ifndef CLIENT_COMPONENT_H_
#define CLIENT_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class ClientComponent: public ClientComponentBase {

	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the ClientComponent.
		 * @param entity The entity that owns the component instance.
		 * @param clientData An initialization parameter.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		ClientComponent(Entity& entity, gclient_t* clientData);

		// ///////////////////// //

		gclient_t* GetClientData() {
			return clientData;
		}

	private:

};

#endif // CLIENT_COMPONENT_H_

