/*
===========================================================================

Unvanquished GPL Source Code
Copyright (C) 2014 Unvanquished Developers

This file is part of the Unvanquished GPL Source Code (Unvanquished Source Code).

Unvanquished Source Code is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Unvanquished Source Code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Unvanquished Source Code.  If not, see <http://www.gnu.org/licenses/>.

===========================================================================
*/

#ifndef SGAME_IGNITABLE_COMPONENT_H_
#define SGAME_IGNITABLE_COMPONENT_H_

#include "../g_local.h"

class IgnitableComponent: public IgnitableComponentBase {
	//friend class Entity;

	public:
		/**
		 * @brief Default constructor of the IgnitableComponent.
		 * @param entity The entity that owns the component instance.
		 * @param alwaysOnFire
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		IgnitableComponent(Entity* entity, bool alwaysOnFire);

	//protected:
		/**
		 * @brief Handle the PrepareNetCode message.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandlePrepareNetCode();

		/**
		 * @brief Handle the Ignite message.
		 * @param fireStarter
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleIgnite(gentity_t* fireStarter);

		/**
		 * @brief Handle the Extinguish message.
		 * @param immunityTime
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleExtinguish(int immunityTime);

		/**
		 * @brief Handle the Think message.
		 * @param timeDelta
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		void HandleThink(int timeDelta);

	private:
		gentity_t* fireStarter = nullptr; /**< Client who orginally started the fire. */
		bool onFire;
		int immuneUntil;
		int nextSelfDamage;
		int nextSplashDamage;
		int nextStatusAction; /**< Time when burn stop or fire spread chances are evaluated. */
};

#endif // SGAME_IGNITABLE_COMPONENT_H_
