#ifndef THINKING_COMPONENT_H_
#define THINKING_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class ThinkingComponent: public ThinkingComponentBase {

	public:
		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the ThinkingComponent.
		 * @param entity The entity that owns the component instance.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		ThinkingComponent(Entity& entity);

		// /////////////////// //
		// Handwritten Members //
		// /////////////////// //

		void Think(int timeDelta);

	private:
		// /////////////////// //
		// Handwritten Members //
		// /////////////////// //

};

#endif // THINKING_COMPONENT_H_

