trap_Error                            -1
trap_Print                            -2
trap_Milliseconds                     -3
trap_Cvar_Register                    -4
trap_Cvar_Update                      -5
trap_Cvar_Set                         -6
trap_Cvar_VariableValue               -7
trap_Cvar_VariableStringBuffer        -8
trap_Cvar_LatchedVariableStringBuffer -9
trap_Cvar_SetValue                    -10
trap_Cvar_Reset                       -11
trap_Cvar_Create                      -12
trap_Cvar_InfoStringBuffer            -13
trap_Argc                             -14
trap_Argv                             -15
trap_Cmd_ExecuteText                  -16
trap_AddCommand                       -17
trap_FS_FOpenFile                     -18
trap_FS_Read                          -19
trap_FS_Write                         -20
trap_FS_FCloseFile                    -21
trap_FS_Delete                        -22
trap_FS_GetFileList                   -23
trap_FS_Seek                          -24
trap_R_RegisterModel                  -25
trap_R_RegisterSkin                   -26
trap_R_RegisterShaderNoMip            -27
trap_R_ClearScene                     -28
trap_R_AddRefEntityToScene            -29
trap_R_AddPolyToScene                 -30
trap_R_AddPolysToScene                -31
trap_R_AddLightToScene                -32
trap_R_AddCoronaToScene               -33
trap_R_RenderScene                    -34
trap_R_SetColor                       -35
trap_R_SetClipRegion                  -36
trap_R_Add2dPolys                     -37
trap_R_DrawStretchPic                 -38
trap_R_DrawRotatedPic                 -39
trap_R_ModelBounds                    -40
trap_UpdateScreen                     -41
trap_CM_LerpTag                       -42
trap_S_RegisterSound                  -43
trap_S_StartLocalSound                -44
trap_S_FadeBackgroundTrack            -45
trap_S_FadeAllSound                   -46
trap_Key_KeynumToStringBuf            -47
trap_Key_GetBindingBuf                -48
trap_Key_SetBinding                   -49
trap_Key_KeysForBinding               -50
trap_Key_IsDown                       -51
trap_Key_GetOverstrikeMode            -52
trap_Key_SetOverstrikeMode            -53
trap_Key_ClearStates                  -54
trap_Key_GetCatcher                   -55
trap_Key_SetCatcher                   -56
trap_GetClipboardData                 -57
trap_GetClientState                   -58
trap_GetGlconfig                      -59
trap_GetConfigString                  -60
trap_LAN_LoadCachedServers            -61
trap_LAN_SaveCachedServers            -62
trap_LAN_AddServer                    -63
trap_LAN_RemoveServer                 -64
trap_LAN_GetPingQueueCount            -65
trap_LAN_ClearPing                    -66
trap_LAN_GetPing                      -67
trap_LAN_GetPingInfo                  -68
trap_LAN_GetServerCount               -69
trap_LAN_GetServerAddressString       -70
trap_LAN_GetServerInfo                -71
trap_LAN_GetServerPing                -72
trap_LAN_MarkServerVisible            -73
trap_LAN_ServerIsVisible              -74
trap_LAN_UpdateVisiblePings           -75
trap_LAN_ResetPings                   -76
trap_LAN_ServerStatus                 -77
trap_LAN_ServerIsInFavoriteList       -78
trap_GetNews                          -79
trap_LAN_CompareServers               -80
trap_MemoryRemaining                  -81
trap_GetCDKey                         -82
trap_SetCDKey                         -83
trap_R_RegisterFont                   -84
memset                                -85
memcpy                                -86
strncpy                               -87
sin                                   -88
cos                                   -89
atan2                                 -90
sqrt                                  -91
floor                                 -92
ceil                                  -93
trap_Parse_AddGlobalDefine            -94
trap_Parse_LoadSource                 -95
trap_Parse_FreeSource                 -96
trap_Parse_ReadToken                  -97
trap_Parse_SourceFileAndLine          -98
trap_PC_AddGlobalDefine               -99
trap_PC_RemoveAllGlobalDefines        -100
trap_PC_LoadSource                    -101
trap_PC_FreeSource                    -102
trap_PC_ReadToken                     -103
trap_PC_SourceFileAndLine             -104
trap_PC_UnReadToken                   -105
trap_S_StopBackgroundTrack            -106
trap_S_StartBackgroundTrack           -107
trap_RealTime                         -108
trap_CIN_PlayCinematic                -109
trap_CIN_StopCinematic                -110
trap_CIN_RunCinematic                 -111
trap_CIN_DrawCinematic                -112
trap_CIN_SetExtents                   -113
trap_R_RemapShader                    -114
trap_GetLimboString                   -115
trap_TranslateString                  -116
trap_CheckAutoUpdate                  -117
trap_GetAutoUpdate                    -118
trap_openURL                          -119
trap_GetHunkData                      -120
trap_R_RegisterAnimation              -121
trap_R_BuildSkeleton                  -122
trap_R_BlendSkeleton                  -123
trap_R_BoneIndex                      -124
trap_R_AnimNumFrames                  -125
trap_R_AnimFrameRate                  -126
trap_R_Glyph                          -301
trap_R_GlyphChar                      -302
trap_R_UnregisterFont                 -303
