#! /usr/bin/env bash

# CC0 1.0 Unvanquished·Developers

set -e

program_dir="$(set -o physical; cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

cd "${program_dir}"

temp_file="$(mktemp)"

last_tag="$(grep '^unvanquished' 'changelog' | head -n1 | sed -e 's/.*(\([^()]*\)-[^()]*).*/\1/')"

cp -a 'changelog' "${temp_file}"

git tag | grep '^v' | grep -v last-compat | sort -n -t. -k 2 | grep "${last_tag}" -A 9999 | tail -n +2 | tac \
| while read tag_name
do
	version_number="$(echo "${tag_name}" | sed -e 's/^v//')"
	version_name="$(echo "${version_number}" | sed -e 's/0./beta /')"
	commit_author="$(git show "${tag_name}" | grep '^Author:' | sed -e 's/^Author:[\t ]*//')"
	tagger_author="$(git show "${tag_name}" | grep '^Tagger:' | sed -e 's/^Tagger:[\t ]*//')"
	tag_date="$(git show "${tag_name}" | grep '^Date:' | head -n 1 | sed -e 's/^Date:[\t ]*//')"
	changelog_date="$(echo "${tag_date}" | sed -e 's/\([A-Za-z]\+\) \([A-Za-z]\+\) \([0-9]\+\) \([0-9:]\+\) \([0-9]\+\) \([0-9+-]\+\)/\1, \3 \2 \5 \4 \6/')"

	if [ -z "${tagger_author}" ]
	then
		tagger_author="${commit_author}"
	fi

	cat <<-EOF
	unvanquished (${version_number}-1) unstable; urgency=low

	  * Release of ${version_name}.

	 -- ${tagger_author}  ${changelog_date}

	EOF
done

cat "${temp_file}"

rm "${temp_file}"
