obj-*-*-*/daemon.*			usr/lib/games/unvanquished/
obj-*-*-*/*.so				usr/lib/games/unvanquished/
obj-*-*-*/main/cgame*.so		usr/lib/games/unvanquished/main/
obj-*-*-*/main/ui*.so			usr/lib/games/unvanquished/main/

#src/gamelogic/base/ui			usr/share/games/unvanquished/base/
#main					usr/share/games/unvanquished/
#src/gamelogic/gpp/ui			usr/share/games/unvanquished/gpp/
#src/gamelogic/base/ui			usr/lib/games/unvanquished/base/
#main					usr/lib/games/unvanquished/
#src/gamelogic/gpp/ui			usr/lib/games/unvanquished/gpp/

debian/unvanquished.sh			usr/games/
debian/unvanquished-download-paks.sh	usr/sbin/
download-pk3.sh				usr/lib/games/unvanquished/

debian/unvanquished.desktop		usr/share/applications/
debian/unvanquished.png			usr/share/icons/hicolor/128x128/apps/
