code

equ trap_Print                            -1
equ trap_Error                            -2
equ trap_Milliseconds                     -3
equ trap_Cvar_Register                    -4
equ trap_Cvar_Update                      -5
equ trap_Cvar_Set                         -6
equ trap_Cvar_VariableStringBuffer        -7
equ trap_Cvar_LatchedVariableStringBuffer -8
equ trap_Argc                             -9
equ trap_Argv                             -10
equ trap_Args                             -11
equ trap_LiteralArgs                      -12
equ trap_GetDemoState                     -13
equ trap_GetDemoPos                       -14
equ trap_FS_FOpenFile                     -15
equ trap_FS_Read                          -16
equ trap_FS_Write                         -17
equ trap_FS_FCloseFile                    -18
equ trap_FS_GetFileList                   -19
equ trap_FS_Delete                        -20
equ trap_SendConsoleCommand               -21
equ trap_AddCommand                       -22
equ trap_RemoveCommand                    -23
equ trap_SendClientCommand                -24
equ trap_UpdateScreen                     -25
equ trap_CM_LoadMap                       -26
equ trap_CM_NumInlineModels               -27
equ trap_CM_InlineModel                   -28
equ trap_CM_TempBoxModel                  -29
equ trap_CM_TempCapsuleModel              -30
equ trap_CM_PointContents                 -31
equ trap_CM_TransformedPointContents      -32
equ trap_CM_BoxTrace                      -33
equ trap_CM_TransformedBoxTrace           -34
equ trap_CM_CapsuleTrace                  -35
equ trap_CM_TransformedCapsuleTrace       -36
equ trap_CM_BiSphereTrace                 -37
equ trap_CM_TransformedBiSphereTrace      -38
equ trap_CM_MarkFragments                 -39
equ trap_R_ProjectDecal                   -40
equ trap_R_ClearDecals                    -41
equ trap_S_StartSound                     -42
equ trap_S_StartSoundVControl             -42
equ trap_S_StartSoundEx                   -43
equ trap_S_StartLocalSound                -44
equ trap_S_ClearLoopingSounds             -45
equ trap_S_ClearSounds                    -46
equ trap_S_AddLoopingSound                -47
equ trap_S_AddRealLoopingSound            -48
equ trap_S_StopLoopingSound               -49
equ trap_S_StopStreamingSound             -50
equ trap_S_UpdateEntityPosition           -51
equ trap_S_GetVoiceAmplitude              -52
equ trap_S_GetSoundLength                 -53
equ trap_S_GetCurrentSoundTime            -54
equ trap_S_Respatialize                   -55
equ trap_S_RegisterSound                  -56
equ trap_S_StartBackgroundTrack           -57
equ trap_S_FadeBackgroundTrack            -58
equ trap_S_StartStreamingSound            -59
equ trap_R_LoadWorldMap                   -60
equ trap_R_RegisterModel                  -61
equ trap_R_RegisterSkin                   -62
equ trap_R_GetSkinModel                   -63
equ trap_R_GetShaderFromModel             -64
equ trap_R_RegisterShader                 -65
equ trap_R_RegisterFont                   -66
equ trap_R_RegisterShaderNoMip            -67
equ trap_R_RegisterShaderLightAttenuation -68
equ trap_R_ClearScene                     -69
equ trap_R_AddRefEntityToScene            -70
equ trap_R_AddRefLightToScene             -71
equ trap_R_AddPolyToScene                 -72
equ trap_R_AddPolysToScene                -73
equ trap_R_AddPolyBufferToScene           -74
equ trap_R_AddLightToScene                -75
equ trap_R_AddAdditiveLightToScene        -76
equ trap_GS_FS_Seek                       -77
equ trap_R_AddCoronaToScene               -78
equ trap_R_SetFog                         -79
equ trap_R_SetGlobalFog                   -80
equ trap_R_RenderScene                    -81
equ trap_R_SaveViewParms                  -82
equ trap_R_RestoreViewParms               -83
equ trap_R_SetColor                       -84
equ trap_R_SetClipRegion                  -85
equ trap_R_DrawStretchPic                 -86
equ trap_R_DrawRotatedPic                 -87
equ trap_R_DrawStretchPicGradient         -88
equ trap_R_Add2dPolys                     -89
equ trap_R_ModelBounds                    -90
equ trap_R_LerpTag                        -91
equ trap_GetGlconfig                      -92
equ trap_GetGameState                     -93
equ trap_GetCurrentSnapshotNumber         -94
equ trap_GetSnapshot                      -95
equ trap_GetServerCommand                 -96
equ trap_GetCurrentCmdNumber              -97
equ trap_GetUserCmd                       -98
equ trap_SetUserCmdValue                  -99
equ trap_SetClientLerpOrigin              -100
equ trap_MemoryRemaining                  -101
equ trap_Key_IsDown                       -102
equ trap_Key_GetCatcher                   -103
equ trap_Key_SetCatcher                   -104
equ trap_Key_GetKey                       -105
equ trap_Key_GetOverstrikeMode            -106
equ trap_Key_SetOverstrikeMode            -107
equ memset                                -108
equ memcpy                                -109
equ strncpy                               -110
equ sin                                   -111
equ cos                                   -112
equ atan2                                 -113
equ sqrt                                  -114
equ floor                                 -115
equ ceil                                  -116
equ trap_PC_AddGlobalDefine               -118
equ trap_PC_LoadSource                    -119
equ trap_PC_FreeSource                    -120
equ trap_PC_ReadToken                     -121
equ trap_PC_SourceFileAndLine             -122
equ trap_PC_UnReadToken                   -123
equ trap_S_StopBackgroundTrack            -124
equ trap_RealTime                         -125
equ trap_SnapVector                       -126
equ trap_CIN_PlayCinematic                -127
equ trap_CIN_StopCinematic                -128
equ trap_CIN_RunCinematic                 -129
equ trap_CIN_DrawCinematic                -130
equ trap_CIN_SetExtents                   -131
equ trap_R_RemapShader                    -132
equ trap_loadCamera                       -135
equ trap_startCamera                      -136
equ trap_stopCamera                       -137
equ trap_getCameraInfo                    -138
equ trap_GetEntityToken                   -139
equ trap_UI_Popup                         -140
equ trap_UI_ClosePopup                    -141
equ trap_Key_GetBindingBuf                -142
equ trap_Key_SetBinding                   -143
equ trap_Parse_AddGlobalDefine            -144
equ trap_Parse_LoadSource                 -145
equ trap_Parse_FreeSource                 -146
equ trap_Parse_ReadToken                  -147
equ trap_Parse_SourceFileAndLine          -148
equ trap_Key_KeynumToStringBuf            -149
equ trap_Key_KeysForBinding               -150
equ trap_CG_TranslateString               -151
equ trap_S_FadeAllSound                   -152
equ trap_R_inPVS                          -153
equ trap_GetHunkData                      -154
equ trap_PumpEventLoop                    -155
equ trap_SendMessage                      -156
equ trap_MessageStatus                    -157
equ trap_R_LoadDynamicShader              -158
equ trap_R_RenderToTexture                -159
equ trap_R_GetTextureId                   -160
equ trap_R_Finish                         -161
equ trap_GetDemoName                      -162
equ trap_R_LightForPoint                  -163
equ trap_S_SoundDuration                  -164
equ trap_R_RegisterAnimation              -165
equ trap_R_CheckSkeleton                  -166
equ trap_R_BuildSkeleton                  -167
equ trap_R_BlendSkeleton                  -168
equ trap_R_BoneIndex                      -169
equ trap_R_AnimNumFrames                  -170
equ trap_R_AnimFrameRate                  -171
equ trap_CompleteCallback                 -172
equ trap_RegisterButtonCommands           -173
equ trap_GetClipboardData                 -174
equ trap_R_Glyph                          -302
equ trap_R_GlyphChar                      -303
equ trap_R_UnregisterFont                 -304
