// _unsorted.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 329 total shaders

// ydnar: removed a ton of redundant "alphaGen vertex" directives

allied_covertops
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/covertops.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

allied_eng
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/eng.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

allied_lt
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/lt.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

allied_medic
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/medic.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

allied_soldier
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/soldier.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

alliedhelmet
{
	nomipmap
	nopicmip
	{
		clampmap gfx/2d/lives_allies.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

axis_covertops
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/covertops_ger.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

axis_eng
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/eng_ger.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

axis_lt
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/LT_ger.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

axis_medic
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/medic_ger.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

axis_soldier
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/soldier_ger.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

axishelmet
{
	nomipmap
	nopicmip
	{
		clampmap gfx/2d/lives_axis.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

blackgrad
{
	nomipmaps
	nopicmip
	{
		map ui/assets/BLACKGRAD.tga
		blendfunc blend
	}
}

blacksmokeanimb1
{
	cull none
	nofog
	{
		map sprites/explode1/spr000.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb2
{
	cull none
	nofog
	{
		map sprites/explode1/spr001.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb3
{
	cull none
	nofog
	{
		map sprites/explode1/spr002.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb4
{
	cull none
	nofog
	{
		map sprites/explode1/spr003.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb5
{
	cull none
	nofog
	{
		map sprites/explode1/spr004.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb6
{
	cull none
	nofog
	{
		map sprites/explode1/spr005.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb7
{
	cull none
	nofog
	{
		map sprites/explode1/spr006.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb8
{
	cull none
	nofog
	{
		map sprites/explode1/spr007.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb9
{
	cull none
	nofog
	{
		map sprites/explode1/spr008.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb10
{
	cull none
	nofog
	{
		map sprites/explode1/spr009.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb11
{
	cull none
	nofog
	{
		map sprites/explode1/spr010.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb12
{
	cull none
	nofog
	{
		map sprites/explode1/spr011.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb13
{
	cull none
	nofog
	{
		map sprites/explode1/spr012.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb14
{
	cull none
	nofog
	{
		map sprites/explode1/spr013.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb15
{
	cull none
	nofog
	{
		map sprites/explode1/spr014.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb16
{
	cull none
	nofog
	{
		map sprites/explode1/spr015.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb17
{
	cull none
	nofog
	{
		map sprites/explode1/spr016.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb18
{
	cull none
	nofog
	{
		map sprites/explode1/spr017.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb19
{
	cull none
	nofog
	{
		map sprites/explode1/spr018.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb20
{
	cull none
	nofog
	{
		map sprites/explode1/spr019.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb21
{
	cull none
	nofog
	{
		map sprites/explode1/spr020.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb22
{
	cull none
	nofog
	{
		map sprites/explode1/spr021.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb23
{
	cull none
	nofog
	{
		map sprites/explode1/spr022.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimb24
{
	cull none
	nofog
	{
		map sprites/explode1/spr022.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanimc1
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr000.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc2
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr001.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc3
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr002.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc4
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr003.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc5
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr004.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc6
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr005.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc7
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr006.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc8
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr007.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc9
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr008.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc10
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr009.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc11
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr010.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc12
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr011.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc13
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr012.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc14
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr013.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc15
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr014.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc16
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr015.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc17
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr016.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc18
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr017.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc19
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr018.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc20
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr019.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc21
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr020.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc22
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr021.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanimc23
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr022.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.5
	}
}

blacksmokeanim1
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr000.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim2
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr001.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim3
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr002.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim4
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr003.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim5
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr004.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim6
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr005.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim7
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr006.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim8
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr007.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim9
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr008.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim10
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr009.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim11
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr010.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim12
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr011.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim13
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr012.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim14
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr013.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim15
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr014.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim16
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr015.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim17
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr016.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim18
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr017.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim19
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr018.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim20
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr019.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim21
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr020.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim22
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr021.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blacksmokeanim23
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr022.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		alphaGen const 0.2
	}
}

blood_dot1
{
	polygonOffset
	{
		map sprites/blood_dot1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

blood_dot2
{
	polygonOffset
	{
		map sprites/blood_dot2.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

blood_dot3
{
	polygonOffset
	{
		map sprites/blood_dot3.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

blood_dot4
{
	polygonOffset
	{
		map sprites/blood_dot4.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

blood_dot5
{
	polygonOffset
	{
		map sprites/blood_dot5.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

bloodcloud
{
	cull none
	entityMergable
	{
		map sprites/bloodcloud.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

bloodexplosion
{
	cull disable
	{
		animmap 5 models/weaphits/blood201.tga models/weaphits/blood202.tga models/weaphits/blood203.tga models/weaphits/blood204.tga models/weaphits/blood205.tga
		blendfunc blend
	}
}

bloodmark
{
	polygonOffset
	{
		map models/weaphits/blood201.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

bloodtrail
{
	entityMergable
	{
		map sprites/blood_dot4.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

blood1
{
	cull disable
	{
		map models/weaphits/blood201.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

blood2
{
	cull disable
	{
		map models/weaphits/blood202.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

blood3
{
	cull disable
	{
		map models/weaphits/blood203.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

blood4
{
	cull disable
	{
		map models/weaphits/blood204.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

blood5
{
	cull disable
	{
		map models/weaphits/blood205.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

bulletparticletrail
{
	cull none
	entityMergable
	{
		map sprites/bullettrail.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

bullet1
{
	cull disable
	sort additive
	{
		map models/weaphits/bullet1.tga
		blendfunc GL_ONE GL_ONE
		rgbGen oneMinusEntity
	}
	{
		map models/weaphits/bullet2.tga
		blendfunc GL_ONE GL_ONE
		rgbGen entity
	}
}

bullet2
{
	cull disable
	sort additive
	{
		map models/weaphits/bullet2.tga
		blendfunc GL_ONE GL_ONE
		rgbGen oneMinusEntity
	}
	{
		map models/weaphits/bullet3.tga
		blendfunc GL_ONE GL_ONE
		rgbGen entity
	}
}

bullet3
{
	cull disable
	sort additive
	{
		map models/weaphits/bullet3.tga
		blendfunc GL_ONE GL_ONE
		rgbGen oneminusentity
	}
}

console2_old
{
	nocompress
	nopicmip
	{
		map ui/assets/wolficonback4.tga
		blendfunc blend
	}
}

console-16bit
{
	nopicmip
	{
		map textures/skies_sd/wurzburg_clouds.tga
		rgbGen identityLighting
		tcMod scale 1.5 .75
		tcMod scroll 0.01 -0.005
	}
	{
		map textures/skies_sd/wurzburg_clouds.tga
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen identityLighting
		tcMod scale 1.25 .85
		tcMod transform 0 1 1 0 0 0
		tcMod scroll 0.03 -0.015
	}
	{
		map textures/skies_sd/ydnar_lightning.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle -8 9 0.33 0.137
		alphaGen wave noise -3 4 0 2.37
		tcMod scale 2 1
		tcMod scroll 0.002 -0.0025
	}
	{
		clampmap textures/skies_sd/colditz_mask.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identityLighting
		tcMod scale 0.85 0.5
		tcMod transform 1 0 0 1 -0.075 0.42
	}
}

console-16bit_old
{
	nocompress
	nopicmip
	{
		map ui/assets/SMOKE-16bit.tga
		blendfunc GL_ONE GL_ZERO
		rgbGen const ( 0.3 0.3 0.3 )
		tcmod scale 1.5 .75
		tcmod scroll 0.025 .05
	}
	{
		map ui/assets/SMOKE-16bit.tga
		blendfunc GL_ONE GL_ONE
		rgbGen const ( 0.2 0.2 0.2 )
		tcmod scale .5 .25
		tcmod scroll 0 .05
	}
}

console2-16bit
{
	nopicmip
	{
		map ui/assets/et_logo.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		alphaGen const 0.1
	}
}

console2-16bit_old
{
	nocompress
	nopicmip
	{
		map ui/assets/wolficonback4.tga
		blendfunc blend
	}
}

debugportals
{
	cull none
	sort additive
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	{
		map _white
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen vertex
	}
}

debugsurfaces
{
	sort opaque
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	{
		map _default
		rgbGen vertex
	}
}

dirt_splash
{
	entityMergable
	nopicmip
	{
		map models/weaphits/sand_splash.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

dlightshader
{
	{
		map $dlight
		blendfunc GL_DST_COLOR GL_ONE
	}
}

entityonfire1
{
	cull none
	deformVertexes wave 45 sin 0 10 0 -.6
	nomipmap
	nopicmip
	{
		animmap 20 sprites/clnfire/spr000.tga sprites/clnfire/spr001.tga sprites/clnfire/spr002.tga sprites/clnfire/spr003.tga sprites/clnfire/spr004.tga sprites/clnfire/spr005.tga sprites/clnfire/spr006.tga sprites/clnfire/spr007.tga sprites/clnfire/spr008.tga sprites/clnfire/spr009.tga sprites/clnfire/spr010.tga sprites/clnfire/spr011.tga sprites/clnfire/spr012.tga sprites/clnfire/spr013.tga sprites/clnfire/spr014.tga sprites/clnfire/spr015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		alphaGen normalzfade 1.0 -0.7 0.5
	}
}

entityonfire2
{
	nomipmap
	nopicmip
	{
		animmap 20 sprites/clnfire/spr000.tga sprites/clnfire/spr001.tga sprites/clnfire/spr002.tga sprites/clnfire/spr003.tga sprites/clnfire/spr004.tga sprites/clnfire/spr005.tga sprites/clnfire/spr006.tga sprites/clnfire/spr007.tga sprites/clnfire/spr008.tga sprites/clnfire/spr009.tga sprites/clnfire/spr010.tga sprites/clnfire/spr011.tga sprites/clnfire/spr012.tga sprites/clnfire/spr013.tga sprites/clnfire/spr014.tga sprites/clnfire/spr015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		alphaGen normalzfade 1.0 -0.7 1.3
	}
	{
		map sprites/inferno_blue.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		alphaGen normalzfade 1.0 -2.0 0.6
	}
}

explode11
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr000.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode12
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr001.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode13
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr002.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode14
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr003.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode15
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr004.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode16
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr005.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode17
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr006.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode18
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr007.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode19
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr008.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode110
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr009.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode111
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr010.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode112
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr011.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode113
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr012.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode114
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr013.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode115
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr014.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode116
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr015.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode117
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr016.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode118
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr017.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode119
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr018.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode120
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr019.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode121
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr020.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode122
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr021.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

explode123
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/explode1/spr022.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

filmnoise
{
	nocompress
	nomipmaps
	nopicmip
	{
		map ui/assets/noise1.tga
		blendfunc gl_one gl_one
		rgbgen wave inversesawtooth .05 .05 0 200
		tcmod scale 2 2
		tcmod scroll 3 3
	}
	{
		map ui/assets/noise2.tga
		blendfunc gl_dst_color gl_one
		rgbgen wave sawtooth .05 .05 0.75 200
		tcmod scale 2 2
		tcmod scroll -3 -3
	}
}

flame
{
	nomipmaps
	nopicmip
	{
		map ui/assets/flame.tga
		blendfunc blend
		tcmod scale .75 .75
		tcmod scroll 0 .1
		tcmod turb .5 .1 0 .15
	}
	{
		map ui/assets/flame.tga
		blendfunc blend
		tcmod scale .5 .5
		tcmod scroll 0 .05
	}
}

flamedlightshader
{
	{
		map $dlight
		blendfunc GL_DST_COLOR GL_ONE
	}
	{
		map $dlight
		blendfunc GL_DST_COLOR GL_ONE
	}
	{
		map $dlight
		blendfunc GL_DST_COLOR GL_ONE
	}
}

flamethrowerbluestream
{
	cull none
	{
		map sprites/fthrow_bluestream1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

flamethrowerfirestream
{
	cull none
	entityMergable
	nofog
	{
		map sprites/fthrow_firestream2.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

flamethrowerfire1
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr000.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire2
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr001.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire3
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr002.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire4
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr003.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire5
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr004.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire6
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr005.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire7
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr006.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire8
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr007.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire9
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr008.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire10
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr009.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire11
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr010.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire12
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr011.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire13
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr012.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire14
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr013.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire15
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr014.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire16
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr015.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire17
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr016.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire18
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr017.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire19
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr018.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire20
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr019.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire21
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr020.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire22
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr021.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire23
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr022.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire24
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr023.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire25
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr024.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire26
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr025.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire27
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr026.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire28
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr027.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire29
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr028.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire30
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr029.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire31
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr030.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire32
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr031.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire33
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr032.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire34
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr033.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire35
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr034.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire36
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr035.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire37
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr036.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire38
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr037.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire39
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr038.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire40
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr039.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire41
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr040.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire42
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr041.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire43
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr042.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire44
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr043.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flamethrowerfire45
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr044.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

flareshader
{
	cull none
	nofog
	nopicmip
	{
		map gfx/misc/flare5.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen vertex
	}
}

fleshimpactsmokepuff
{
	cull none
	entityMergable
	nofog
	{
		map gfx/misc/smokepuffflesh.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

gold_line
{
	nomipmaps
	nopicmip
	{
		map ui/assets/gold_line.tga
		blendfunc blend
	}
}

grenadeexplosion
{
	cull disable
	{
		animmap 7 gfx/colors/ablack.tga sprites/fire_sm_a.tga sprites/fire_sm_b.tga sprites/fire_sm_c.tga sprites/fire_sm_d.tga sprites/fire_sm_e.tga sprites/fire_sm_f.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave inversesawtooth 0 1 0 7
	}
	{
		animmap 7 sprites/fire_sm_a.tga sprites/fire_sm_b.tga sprites/fire_sm_c.tga sprites/fire_sm_d.tga sprites/fire_sm_e.tga sprites/fire_sm_f.tga gfx/colors/ablack.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 7
	}
}

jpwhud1
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/classic1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud2
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/pistol1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud3
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/mp401.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud4
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/minigun1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud5
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/knife1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwtest1
{
	cull none
	entityMergable
	nofog
	{
		clampmap gfx/2d/mp401.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwtest2
{
	cull none
	entityMergable
	nofog
	{
		clampmap gfx/2d/pistol1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

lagometer
{
	nopicmip
	{
		map gfx/2d/lag.tga
	}
}

lightbeam
{
	cull none
	sort nearest
	{
		map *white
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

markshadow
{
	polygonOffset
	{
		map sprites/shadow_soft.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}

markshadowfoot
{
	polygonOffset
	{
		map sprites/shadow_foot.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}

markshadowtorso
{
	polygonOffset
	{
		map sprites/shadow_torso.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}

menu_select
{
	nomipmaps
	nopicmip
	{
		map ui/assets/menu_select.tga
		blendfunc blend
	}
}

multi_alliedflag
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/alliedflag.tga
	}
	{
		map ui/assets/portraits/stars.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod scroll -.125 -.125
	}
}

multi_axisflag
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/axisflag.tga
	}
	{
		map ui/assets/portraits/wolflogo.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod scroll 0.125 0
	}
}

multi_spectator
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/spectator.tga
	}
}

negdlightshader
{
	{
		map $dlight
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
	}
}

nozzleflame1
{
	cull none
	nofog
	{
		map sprites/nozzle/noz001.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame2
{
	cull none
	nofog
	{
		map sprites/nozzle/noz002.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame3
{
	cull none
	nofog
	{
		map sprites/nozzle/noz003.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame4
{
	cull none
	nofog
	{
		map sprites/nozzle/noz004.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame5
{
	cull none
	nofog
	{
		map sprites/nozzle/noz005.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame6
{
	cull none
	nofog
	{
		map sprites/nozzle/noz006.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame7
{
	cull none
	nofog
	{
		map sprites/nozzle/noz007.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

nozzleflame8
{
	cull none
	nofog
	{
		map sprites/nozzle/noz008.tga
		blendfunc GL_ONE GL_ONE_MINUS_SRC_COLOR
		rgbGen vertex
	}
}

oilparticle
{
	cull none
	entityMergable
	{
		map sprites/oil_PARTICLE.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

oilslick
{
	entityMergable
	polygonOffset
	surfaceparm slick
	{
		map textures/decals/oil_slick.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
	{
		map textures/effects/wdfx_W.tga
		blendFunc GL_ONE_MINUS_DST_ALPHA GL_ONE
		tcGen environment
		tcmod scale 2 2
	}
}

powerbar
{
	nocompress
	nomipmap
	nopicmip
	{
		map ui/assets/hudpower.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

projectionshadow
{
	deformVertexes projectionShadow
	polygonOffset
	{
		map *white
		blendFunc GL_ONE GL_ZERO
		rgbGen wave square 0 0 0 0
	}
}

q3view_ground
{
	{
		map $checkimage
	}
}

railcore
{
	cull none
	sort nearest
	{
		map gfx/misc/railcorethin_mono.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
		tcMod scroll -1 0
	}
}

rocketexplosion
{
	cull disable
	{
		animmap 7 gfx/colors/ablack.tga sprites/fire_sm_a.tga sprites/fire_sm_b.tga sprites/fire_sm_c.tga sprites/fire_sm_d.tga sprites/fire_sm_e.tga sprites/fire_sm_f.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave inversesawtooth 0 1 0 7
	}
	{
		animmap 7 sprites/fire_sm_a.tga sprites/fire_sm_b.tga sprites/fire_sm_c.tga sprites/fire_sm_d.tga sprites/fire_sm_e.tga sprites/fire_sm_f.tga gfx/colors/ablack.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 7
	}
}

shotgunsmokepuff
{
	cull none
	{
		map gfx/misc/smokepuff2b.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen entity
		alphaGen entity
	}
}

skeletonskin
{
	cull disable
	surfaceparm alphashadow
	{
		map models/mapobjects/skel/skel.tga
		alphaFunc GE128
		rgbGen lightingdiffuse
		alphaGen entity
	}
}

sliderbutt_1
{
	nomipmaps
	nopicmip
	{
		map ui/assets/SLIDERBUTT_1.tga
		blendfunc blend
	}
}

slider2
{
	nomipmaps
	nopicmip
	{
		map ui/assets/SLIDER2.tga
		blendfunc blend
	}
}

smokeparticle
{
	cull none
	{
		map sprites/smokepuff.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

smokepuff
{
	cull none
	entityMergable
	nofog
	{
		map gfx/misc/smokepuff.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

smokepuffblack1
{
	cull none
	{
		map gfx/misc/smokepuff_b1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

smokepuffblack2
{
	cull none
	{
		map gfx/misc/smokepuff_b2.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

smokepuffblack3
{
	cull none
	{
		map gfx/misc/smokepuff_b3.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

smokepuffblack4
{
	cull none
	{
		map gfx/misc/smokepuff_b4.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

smokepuffblack5
{
	cull none
	{
		map gfx/misc/smokepuff_b5.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

smokepuffdirty
{
	cull none
	entityMergable
	{
		map gfx/misc/smokepuff_d.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

smokepuffragepro
{
	cull none
	entityMergable
	{
		map gfx/misc/smokepuffragepro.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

smoketrail
{
	cull none
	entityMergable
	{
		map sprites/smoketrail2.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

snow_tri
{
	cull none
	entityMergable
	{
		map gfx/misc/snow_tri.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

sparkflareparticle
{
	cull none
	entityMergable
	{
		map gfx/misc/sunflare1.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen vertex
	}
}

sparkparticle
{
	cull none
	entityMergable
	{
		map sprites/spark.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen vertex
	}
}

splashripple
{
	{
		clampmap sprites/splashalpha.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		tcMod stretch sawtooth 0 1 0 0.9
	}
}

spotlight
{
	polygonOffset
	{
		clampmap sprites/splashalpha.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

sprintbar
{
	nocompress
	nomipmap
	nopicmip
	{
		clampmap ui/assets/hudsprint.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

sun
{
	cull none
	nocompress
	nofog
	{
		map gfx/misc/sun.tga
		blendFunc blend
		rgbGen vertex
	}
}

sunflare1
{
	cull none
	{
		map gfx/misc/sunflare1.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

teslaaltdamageeffect
{
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
}

tesladamageeffect
{
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
}

twiltb21
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr020.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb22
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr021.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb23
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr022.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb24
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr023.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb25
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr024.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb26
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr025.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb27
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr026.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb28
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr027.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb29
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr028.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb210
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr009.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb211
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr010.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb212
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr011.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb213
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr012.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb214
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr013.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb215
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr014.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb216
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr015.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb217
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr016.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb218
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr017.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb219
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr018.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb220
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr019.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb221
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr020.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb222
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr021.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb223
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr022.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb224
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr023.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb225
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr024.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb226
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr025.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb227
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr026.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb228
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr027.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb229
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr028.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb230
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr029.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb231
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr030.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb232
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr031.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb233
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr032.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb234
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr033.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb235
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr034.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb236
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr035.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb237
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr036.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb238
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr037.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb239
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr038.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb240
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr039.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb241
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr040.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb242
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr041.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb243
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr042.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb244
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr043.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

twiltb245
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/twiltb2/spr044.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_COLOR
	}
}

viewbloodblend1
{
	sort nearest
	{
		map models/weaphits/blood201.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identityLighting
		alphaGen vertex
	}
}

viewbloodblend2
{
	sort nearest
	{
		map models/weaphits/blood202.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identityLighting
		alphaGen vertex
	}
}

viewbloodblend3
{
	sort nearest
	{
		map models/weaphits/blood203.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identityLighting
		alphaGen vertex
	}
}

viewbloodblend4
{
	sort nearest
	{
		map models/weaphits/blood204.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identityLighting
		alphaGen vertex
	}
}

viewbloodblend5
{
	sort nearest
	{
		map models/weaphits/blood205.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identityLighting
		alphaGen vertex
	}
}

viewfadeblack
{
	sort nearest
	{
		map *white
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		rgbGen wave square 0 0 0 0
		alphaGen entity
	}
}

viewflashblood
{
	sort nearest
	{
		map sprites/viewflash_red.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen vertex
	}
}

viewflashfire1
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr000.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire2
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr001.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire3
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr002.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire4
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr003.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire5
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr004.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire6
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr005.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire7
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr006.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire8
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr007.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire9
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr008.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire10
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr009.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire11
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr010.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire12
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr011.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire13
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr012.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire14
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr013.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire15
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr014.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewflashfire16
{
	cull none
	nofog
	nomipmaps
	nopicmip
	{
		map sprites/clnfire/spr015.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
	}
}

viewteslaaltdamageeffect
{
	cull disable
	nofog
	sort nearest
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
}

viewtesladamageeffect
{
	cull disable
	nofog
	sort nearest
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ONE
		rgbGen entity
	}
}

wake
{
	cull none
	nopicmip
	nomipmaps
	
	// pass 1
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0 0.4
		alphaGen wave inversesawtooth	0 1 0 0.4
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0 0.4
		alphaGen wave inversesawtooth	0 1 0 0.4
	}
	
	// pass 2
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.33 0.5
		alphaGen wave inversesawtooth	0 1 0.33 0.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.33 0.5
		alphaGen wave inversesawtooth	0 1 0.33 0.5
	}
	
	// pass 3
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.66 0.4
		alphaGen wave inversesawtooth	0 1 0.66 0.4
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.66 0.4
		alphaGen wave inversesawtooth	0 1 0.66 0.4
	}
}



wakeanim
{
	{
		clampmap sprites/splashalpha.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		tcmod stretch sin 0 1 0 .25
	}
}

water_splash
{
	entityMergable
	nopicmip
	{
		map models/weaphits/water_splash.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

waterbubble
{
	cull none
	entityMergable
	sort underwater
	{
		map sprites/bubble.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

watersplash
{
	cull disable
	{
		animmap 20 models/weaphits/splash2_1.tga models/weaphits/splash2_2.tga models/weaphits/splash2_3.tga models/weaphits/splash2_4.tga gfx/colors/ablack.tga
		blendfunc blend
		alphaGen wave inversesawtooth 0 1 0 4
	}
}

watersplash_almost
{
	cull disable
	{
		animmap 12 models/weaphits/splash2_1.tga models/weaphits/splash2_2.tga models/weaphits/splash2_3.tga models/weaphits/splash2_4.tga gfx/colors/ablack.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen wave inversesawtooth 0 1 0 12
	}
	{
		animmap 12 models/weaphits/splash2_2.tga models/weaphits/splash2_3.tga models/weaphits/splash2_4.tga gfx/colors/ablack.tga gfx/colors/ablack.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen wave sawtooth 0 1 0 12
	}
}

watersplash_test2
{
	cull disable
	{
		animmap 10 models/weaphits/splash2_1.tga models/weaphits/splash2_2.tga models/weaphits/splash2_3.tga models/weaphits/splash2_4.tga
		blendfunc GL_SRC_ALPHA GL_ZERO
	}
}

white
{
	{
		map *white
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

wolfflamelogo
{
	nomipmaps
	nopicmip
	{
		map ui/assets/WOLFFLAMELOGO.tga
		blendfunc blend
	}
}

/models/multiplayer/m1_garand/m1garandscope
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingdiffuse
		tcGen environment
	}
	{
		map models/multiplayer/m1_garand/m1garandscope_yd.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingdiffuse
	}
}
