// assault.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 14 total shaders

textures/assault/atool_m02
{
	surfaceparm metalsteps
	implicitMap -
	
	qer_editorimage textures/assault/atool_m02
	diffusemap		textures/assault/atool_m02
	bumpmap         displacemap( textures/assault/atool_m02_norm invertColor(textures/assault/atool_m02_disp) )
	specularmap		textures/assault/atool_m02_spec
}

textures/assault/atruss_m06a
{
	cull disable
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm pointlight
	surfaceparm trans
	implicitMask -
	
	qer_editorimage textures/assault/atruss_m06a
	diffusemap		textures/assault/atruss_m06a
	bumpmap         displacemap( textures/assault/atruss_m06a_norm invertColor(textures/assault/atruss_m06a_disp) )
	specularmap		textures/assault/atruss_m06a_spec
}

textures/assault/awall_m01
{

	qer_editorimage textures/assault/awall_m01
	diffusemap		textures/assault/awall_m01
	bumpmap         displacemap( textures/assault/awall_m01_norm invertColor(textures/assault/awall_m01_disp) )
	specularmap		textures/assault/awall_m01_spec

}

textures/assault/machine_cl01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c01b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c03a
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c03e
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c04b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c05b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c06b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/machine_c07
{
	surfaceparm metalsteps
	implicitMap -
}

textures/assault/metal_c06
{
	surfaceparm metalsteps
	implicitMap -
	
	qer_editorimage textures/assault/metal_c06
	diffusemap		textures/assault/metal_c06
	bumpmap         displacemap( textures/assault/awall_m01_norm invertColor(textures/assault/metal_c06_disp) )
	specularmap		textures/assault/metal_c06_spec
}

textures/assault/metal_c07a
{
	surfaceparm metalsteps
	implicitMap -
	
	qer_editorimage textures/assault/metal_c07a
	diffusemap		textures/assault/metal_c07a
	bumpmap         displacemap( textures/assault/metal_c07a_norm invertColor(textures/assault/metal_c07a_disp) )
	specularmap		textures/assault/metal_c07a_spec
	
}

textures/assault/metal_c07ans
{
	qer_editorimage textures/assault/metal_c07a
	surfaceparm nonsolid
	surfaceparm trans
	implicitMap textures/assault/metal_c07a
	
	diffusemap		textures/assault/metal_c07a
	bumpmap         displacemap( textures/assault/metal_c07a_norm invertColor(textures/assault/metal_c07a_disp) )
	specularmap		textures/assault/metal_c07a_spec
}

textures/assault/trim_c01
{
	surfaceparm metalsteps
	implicitMap -
}
