// bbmodels_mapobjects.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

bbmodels/mapobjects/skel/skel
{
	cull disable
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm pointlight
	surfaceparm trans
	implicitMask models/mapobjects/skel/skel.tga
}
