// bunker_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 4 total shaders

textures/bunker_sd/extwall01_sand
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/extwall02_sand
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/girder01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/girder02
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/girder03
{
	surfaceparm metalsteps
	implicitMap -
}

textures/bunker_sd/tinroof01
{
	q3map_nonplanar
	q3map_shadeangle 180
	implicitMap -
}

textures/bunker_sd/wirefence01
{
	cull none
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}

// Addition by Eonfge, check that (^^) stuff later 

textures/bunker_sd/concrete_c07bcmp_sand
{
    qer_editorimage textures/bunker_sd/concrete_c07bcmp_sand
	diffusemap		textures/bunker_sd/concrete_c07bcmp_sand
	bumpmap         displacemap( textures/bunker_sd/concrete_c07bcmp_sand_norm, invertColor(textures/bunker_sd/concrete_c07bcmp_sand_disp) )
	specularmap		textures/bunker_sd/concrete_c07bcmp_sand_spec
	
}

textures/bunker_sd/grinder02
{
    qer_editorimage textures/bunker_sd/grinder02
	diffusemap		textures/bunker_sd/grinder02
	bumpmap         displacemap( textures/bunker_sd/grinder03_norm, invertColor(textures/bunker_sd/grinder03_disp) )
	specularmap		textures/bunker_sd/grinder03_spec
	
}

textures/bunker_sd/grinder03
{
    qer_editorimage textures/bunker_sd/grinder03
	diffusemap		textures/bunker_sd/grinder03
	bumpmap         displacemap( textures/bunker_sd/grinder03_norm, invertColor(textures/bunker_sd/grinder03_disp) )
	specularmap		textures/bunker_sd/grinder03_spec
	
}

textures/bunker_sd/int_wall01
{
    qer_editorimage textures/bunker_sd/int_wall01
	diffusemap		textures/bunker_sd/int_wall01
	bumpmap         displacemap( textures/bunker_sd/int_wall01_norm, invertColor(textures/bunker_sd/int_wall01_disp) )
	specularmap		textures/bunker_sd/int_wall01_spec
	
}

textures/bunker_sd/int_wall01_white
{
    qer_editorimage textures/bunker_sd/int_wall01_white
	diffusemap		textures/bunker_sd/int_wall01_white
	bumpmap         displacemap( textures/bunker_sd/int_wall01_norm, invertColor(textures/bunker_sd/int_wall01_disp) )
	specularmap		textures/bunker_sd/int_wall01_spec
	
}

textures/bunker_sd/int_wall01_rusty
{
    qer_editorimage textures/bunker_sd/int_wall01_rusty
	diffusemap		textures/bunker_sd/int_wall01_rusty
	bumpmap         displacemap( textures/bunker_sd/int_wall01_norm, invertColor(textures/bunker_sd/int_wall01_disp) )
	specularmap		textures/bunker_sd/int_wall01_spec
	
}

textures/bunker_sd/int_wall07
{
    qer_editorimage textures/bunker_sd/int_wall07
	diffusemap		textures/bunker_sd/int_wall07
	bumpmap         displacemap( textures/bunker_sd/int_wall01_norm, invertColor(textures/bunker_sd/int_wall01_disp) )
	specularmap		textures/bunker_sd/int_wall01_spec
	
}