// castle_wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 6 total shaders

textures/castle_wood/cwood_c10
{
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_c18
{
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo2s1
{
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo5c
{
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo5cb
{
	surfaceparm woodsteps
	implicitMap -
}

textures/castle_wood/cwood_mo6
{
	surfaceparm woodsteps
	implicitMap -
}
