// chat_window.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

textures/chat_window/chwindow_c05
{
	qer_editorimage textures/chat_window/chwindow_c05.tga
	Q3map_lightimage textures/lightimage/ltblue_m1a.tga
	q3map_surfacelight 300
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chat_window/chwindow_c05.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chat_window/chwindow_c05.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chat_window/chwindow_c06
{
	qer_editorimage textures/chat_window/chwindow_c06.tga
	Q3map_lightimage textures/lightimage/chwindow_c06.tga
	q3map_surfacelight 300
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chat_window/chwindow_c06.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chat_window/chwindow_c06.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}
