// chat.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 11 total shaders

textures/chat/bedlinen_c04
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/book_c02
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chat/book_c03
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chat/book_c05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chat/carpet_c02
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/carpet_c03
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/carpet_c08
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/carpet_c10
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/carpet_c10trim
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/carpet_c11
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/carpet_c14trim
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chat/office_c03
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chat/picture_05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chat/wd_sr_va7
{
	surfaceparm woodsteps
	implicitMap -
}
