// chateau.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 36 total shaders

textures/chateau/desk_c03
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/desk_c04
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/door_c01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/fireplace_01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c04
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/floor_c10
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chateau/floor_c10a
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chateau/pillar_temp_rf
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/stair_c01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/stair_c03
{
	surfaceparm carpetsteps
	implicitMap -
}

textures/chateau/trim_c01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c03
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c08
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c09
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c10
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/trim_c14
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/walltest_c07a_vertex
{
	qer_editorimage chateau/walltest_c07a.tga
	{
		map textures/chateau/walltest_c07a.tga
		rgbGen vertex
		tcMod Scale .25 .25
	}
}

textures/chateau/window_c03a
{
	qer_editorimage textures/chateau/window_c03a.tga
	q3map_lightimage textures/lightimage/soft_blue.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 300
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend.tga
		blendfunc GL_ONE GL_ONE
	}
}

textures/chateau/window_c03a_nolight
{
	qer_editorimage textures/chateau/window_c03a.tga
	implicitMap textures/chateau/window_c03a.tga
}

textures/chateau/window_c03a_750
{
	qer_editorimage textures/chateau/window_c03a.tga
	q3map_lightimage textures/lightimage/soft_blue.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 750
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c03a_1250
{
	qer_editorimage textures/chateau/window_c03a.tga
	q3map_lightimage textures/lightimage/soft_blue.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 1250
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c03a_2500
{
	qer_editorimage textures/chateau/window_c03a.tga
	q3map_lightimage textures/lightimage/soft_blue.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 2500
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c04a
{
	qer_editorimage textures/chateau/window_c04a.tga
	q3map_lightimage textures/lightimage/soft_blue2.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 300
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c04a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c02.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_c07a
{
	qer_editorimage textures/chateau/window_c07a.tga
	q3map_lightimage textures/lightimage/soft_warm.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 80
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c07a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c05.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/window_director
{
	qer_editorimage textures/chateau/window_c03a.tga
	q3map_lightimage textures/lightimage/soft_blue.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 3000
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/chateau/window_c03a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/chateau/window_c01.blend.tga
		blendfunc GL_ONE GL_ONE
		rgbGen identity
	}
}

textures/chateau/wood_c05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c07
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c09
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_c20
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chateau/wood_test
{
	surfaceparm woodsteps
	implicitMap -
}
