// chat_wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

textures/chat_wood/chwood_c02
{
	surfaceparm woodsteps
	implicitMap -
}

textures/chat_wood/chwood_c04
{
	surfaceparm woodsteps
	implicitMap -
}
