// common.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 80 total shaders

textures/common/ai_nopass
{
	qer_editorimage	textures/common/ai_nopass
	qer_trans 0.30
	
	surfaceparm ai_nopass
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/ai_nopasslarge
{
	qer_editorimage	textures/common/ai_nopasslarge
	qer_trans 0.30
	
	surfaceparm ai_nopasslarge
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/ai_nosight
{
	qer_editorimage	textures/common/ai_nosight
	qer_trans 0.3
	
	surfaceparm ai_nosight
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/ai_nosight_shoot_through
{
	qer_editorimage	textures/common/ai_nosight_shoot_through
	qer_trans 0.3
	
	surfaceparm ai_nosight
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm trans
}

//==============================================================================
// portals
//==============================================================================

// visportal brushes stop the area flood fills in xmap and
// define portals, separating the world into areas
textures/common/areaportal
{
	qer_editorimage	textures/common/areaportal.tga
	qer_trans 0.50

	surfaceparm areaportal
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/antiportal
{
	qer_editorimage	textures/common/antiportal
	qer_nocarve
	qer_trans 0.30

	surfaceparm antiportal
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/editor/visportal
{
	qer_editorimage	textures/common/visportal.tga
	qer_trans 0.5
	
	nonsolid
	noshadows
	nomarks
	nolightmap
	//structural
	//areaportal
}

textures/common/caulk
{
	qer_editorimage	textures/common/caulk

	surfaceparm nodraw
	surfaceparm nomarks
}

textures/common/caulkterrain
{
	qer_editorimage	textures/common/caulkterrain

	surfaceparm nodraw
	surfaceparm nomarks
}

textures/common/clip
{
	qer_editorimage	textures/common/clip
	qer_trans 0.3
	
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clip_metal
{
	qer_editorimage	textures/common/clip_metal
	qer_trans 0.3
	
	surfaceparm clipmissile
	surfaceparm metalsteps
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipfull
{
	qer_editorimage	textures/common/clipfull
	qer_trans 0.3
	
	surfaceparm nodraw
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipmissile
{
	qer_editorimage	textures/common/clipmissile
	qer_trans 0.3
	
	surfaceparm clipmissile
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipmonster
{
	qer_editorimage	textures/common/clipmonster
	qer_trans 0.3
	
	surfaceparm monsterclip
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/clipmonster2
{
	qer_editorimage textures/common/clipmonster.tga
	
	surfaceparm monsterclip
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/clipshot
{
	qer_editorimage	textures/common/clipshot
	qer_trans 0.3
	
	surfaceparm clipshot
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/clipweap
{
	qer_editorimage	textures/common/clipweap
	qer_trans 0.3
	
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/clipweap_metal
{
	qer_editorimage	textures/common/clipweap_metal
	qer_editorimage textures/common/clipweapmetal.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

// Don't ask...
textures/common/clipweapmetal
{
    qer_editorimage "textures/common/clip_metal.tga"
    qer_trans 0.3
    
	surfaceparm nodraw
    surfaceparm nomarks
    surfaceparm trans
    surfaceparm metalsteps
}

textures/common/clipweap_wood
{
	qer_editorimage textures/common/clipweapwood.tga
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/clusterportal
{
	qer_editorimage	textures/common/clusterportal
	qer_trans 0.3
	
	surfaceparm clusterportal
	surfaceparm detail
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/cushion
{
	qer_editorimage	textures/common/cushion
	qer_nocarve
	qer_trans 0.5
	
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/hint
{
	qer_editorimage	textures/common/hint
	qer_nocarve
	qer_trans 0.3
	
	surfaceparm hint
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/ladder
{
	qer_editorimage	textures/common/ladder
	qer_trans 0.3
	
	surfaceparm ladder
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/leakoil
{
	qer_editorimage	textures/common/leakoil
	qer_trans 0.5
	
//	surfaceparm markparticles
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/leaksteam
{
	qer_editorimage	textures/common/leaksteam
	qer_trans 0.5
	
//	surfaceparm markparticles
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/leakwater
{
	qer_editorimage	textures/common/leakwater
	qer_trans 0.5
	
//	surfaceparm markparticles
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/lightgrid
{
	qer_editorimage	textures/common/lightgrid
	qer_trans 0.5
	
	surfaceparm detail
	surfaceparm lightgrid
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/lmterrain_sand_marks
{
	qer_editorimage textures/common/terrain_sand.tga
	
	q3map_shadeangle 45
	q3map_terrain
	surfaceparm gravelsteps
	surfaceparm nodraw
}

textures/common/lmterrain_snow_marks
{
	qer_editorimage textures/common/terrain_snow.tga
	
	q3map_shadeangle 90
	q3map_terrain
	surfaceparm nodraw
	surfaceparm snowsteps
}

textures/common/nodraw
{
	qer_editorimage	textures/common/nodraw
	qer_trans 0.3
	
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/nodrawnonsolid
{
	qer_editorimage	textures/common/nodrawnonsolid

	surfaceparm nodraw
	surfaceparm nonsolid
}

textures/common/nodrawwater
{
	qer_editorimage textures/liquids/lake_m1.tga
	qer_trans .5
	
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm water
}

textures/common/nodrop
{
	qer_editorimage	textures/common/nodrop
	qer_nocarve
	qer_trans 0.5
	
	cull disable
	surfaceparm nodraw
	surfaceparm nodrop
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/origin
{
	qer_editorimage	textures/common/origin
	qer_nocarve
	qer_trans 0.3
	
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm origin
	surfaceparm trans
}

textures/common/skip
{
	qer_editorimage	textures/common/skip
	qer_nocarve
	qer_trans 0.30
	
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm skip
	surfaceparm structural
	surfaceparm trans
}

textures/common/slick
{
	qer_editorimage	textures/common/slick
	qer_trans 0.3
	
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm slick
	surfaceparm trans
}

textures/common/slip_c_e
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_n
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_ne
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_nw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_s
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_se
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_sw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_c_w
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm carpetsteps
	surfaceparm monsterslick
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_e
{
	qqer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_e
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_n
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_ne
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_nw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_s
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_se
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_sw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_g_w
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm grasssteps
	surfaceparm monsterslick
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_e
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_n
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_ne
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_nw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_s
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_se
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_sw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_m_w
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm metalsteps
	surfaceparm monsterslick
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_n
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_ne
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_nw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_s
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_se
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_sw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_w
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
}

textures/common/slip_w_e
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_n
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_ne
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicknorth
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_nw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicknorth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_s
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_se
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickeast
	surfaceparm monsterslicksouth
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_sw
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslicksouth
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/slip_w_w
{
	qer_editorimage textures/common/slick.tga
	qer_trans 0.3
	
	surfaceparm monsterslick
	surfaceparm monsterslickwest
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/terrain
{
	qer_editorimage textures/common/terrain.tga
	
	q3map_terrain
	surfaceparm grasssteps
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
}

textures/common/terrain_snow
{
	qer_editorimage textures/common/terrain_snow
	
	q3map_terrain
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
//	surfaceparm snow
	surfaceparm snowsteps
}

textures/common/terrain_snow_wils
{
	qer_editorimage textures/common/terrain_snow_wils
	
	q3map_terrain
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm snowsteps
}

textures/common/terrain2
{
	qer_editorimage textures/common/terrain2
	q3map_terrain
//	surfaceparm dust
	surfaceparm grasssteps
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
}

textures/common/trigger
{
	qer_editorimage textures/common/trigger
	qer_nocarve
	qer_trans 0.5
	
	surfaceparm nodraw
	surfaceparm trans
}
