// eerie.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 3 total shaders

textures/eerie/darkness
{
	cull back
	fogonly
	fogparms 0 0 0 128 128
	surfaceparm fog
	surfaceparm nodrop
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
}

textures/eerie/floor3_3dark
{
	surfaceparm metalsteps
}

textures/eerie/lavafogshader
{
	fogonly
	surfaceparm fog
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
}
