// egypt_rock_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 7 total shaders

textures/egypt_rock_sd/layered_rock_01
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_rock_sd/layered_rock_01_btrim_01
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_rock_sd/layered_rock_01_btrim_01_nero
{
	qer_editorimage textures/egypt_rock_sd/layered_rock_01_btrim_01.tga
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_rock_sd/layered_rock_01_btrim_01.tga
}

textures/egypt_rock_sd/layered_rock_01_nero
{
	qer_editorimage textures/egypt_rock_sd/layered_rock_01.tga
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_rock_sd/layered_rock_01.tga
}

textures/egypt_rock_sd/layered_rock_01_ttrim_01
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}

textures/egypt_rock_sd/layered_rock_01_ttrim_01_nero
{
	qer_editorimage textures/egypt_rock_sd/layered_rock_01_ttrim_01.tga
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap textures/egypt_rock_sd/layered_rock_01_ttrim_01.tga
}

textures/egypt_rock_sd/sandstone_01
{
	q3map_nonplanar
	q3map_shadeangle 90
	implicitMap -
}
