// egypt_wood_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

textures/egypt_wood_sd/wood1a
{
	surfaceparm woodsteps
	implicitMap -
}

textures/egypt_wood_sd/wood1b
{
	surfaceparm woodsteps
	implicitMap -
}
