// egypt_windows_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/egypt_windows_sd/windowtrim01
{
	cull disable
	nomipmaps
	surfaceparm metalsteps
	implicitMask -
}
