// egypt_props_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 9 total shaders

textures/egypt_props_sd/siwa_canvas1
{
	cull disable
	deformVertexes wave 100 sin 0 2 0 .3
	deformVertexes wave 30 sin 0 2 0 .1
	nofog
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	tessSize 64
	implicitMap -
}

textures/egypt_props_sd/siwa_canvas2
{
	qer_editorimage textures/egypt_props_sd/siwa_canvas1.tga
	cull disable
	deformVertexes wave 100 sin 0 1 0 .4
	deformVertexes wave 30 sin 0 1 0 .1
	nofog
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	tessSize 64
	implicitMap textures/egypt_props_sd/siwa_canvas1.tga
}

textures/egypt_props_sd/siwa_carpet1
{
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}

textures/egypt_props_sd/siwa_carpet1anim
{
	qer_editorimage textures/egypt_props_sd/siwa_carpet1.tga
	deformVertexes wave 30 sin 0 3 0 0.2
	surfaceparm alphashadow
	surfaceparm nodamage
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	tessSize 64
	implicitMask textures/egypt_props_sd/siwa_carpet1.tga
}

textures/egypt_props_sd/siwa_carpet2
{
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}

textures/egypt_props_sd/siwa_carpet3
{
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}

textures/egypt_props_sd/siwa_carpet3anim
{
	qer_editorimage textures/egypt_props_sd/siwa_carpet3.tga
	deformVertexes wave 30 sin 0 3 0 0.2
	surfaceparm alphashadow
	surfaceparm nodamage
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	tessSize 64
	implicitMask textures/egypt_props_sd/siwa_carpet3.tga
}

textures/egypt_props_sd/siwa_carpet4
{
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}

textures/egypt_props_sd/siwa_carpet5
{
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm trans
	implicitMask -
}
