// gfx_clipboard.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

gfx/clipboard/document1
{
	nomipmaps
	nopicmip
	{
		map gfx/clipboard/document1.tga
		rgbGen identity
	}
}
