///HELL - DESIGN BY AVOC @ eft-clan.com ///
//////////////////////////////////////////////
///NATURE
////////////////////////

textures/hell/nature/snow_trees
{
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm playerclip
	polygonOffset
	cull none
	q3map_noTJunc
	q3map_noclip
	implicitMask -
}

textures/hell/nature/dark_rock_snowy
{
	q3map_shadeAngle 120
	q3map_nonplanar
	implicitMask -
}