// icons.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 39 total shaders

icons/iconw_ammopack_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_ammopack_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_colt_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_colt_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_dynamite_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_dynamite_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_flamethrower_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_flamethrower_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_grenade_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_grenade_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_knife_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_knife_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_luger_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_luger_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_mauser_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_mauser_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_medheal_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_medheal_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_mp40_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_MP40_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_panzerfaust_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_panzerfaust_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_pineapple_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_pineapple_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_pliers_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_pliers_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_smokegrenade_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_smokegrenade_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_sten_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_sten_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/iconw_thompson_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_thompson_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}


icons/iconw_venom_1_select
{
	nomipmaps
	nopicmip
	{
		map icons/iconw_venom_1_select.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

icons/noammo
{
	nomipmaps
	nopicmip
	{
		map icons/noammo.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}
