// levelshots.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 27 total shaders

levelshots/automap_mask
{
	nopicmip
	nocompress
	nomipmaps
	{
		map gfx/2d/compass_mask.tga
		alphafunc GE128	
	}
}

levelshots/fueldump_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/fueldump_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/fueldump_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/fueldump_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/goldrush_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/goldrush_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/goldrush_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/goldrush_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/railgun_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/railgun_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/railgun_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/railgun_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/battery_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/battery_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/battery_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/battery_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/oasis_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/oasis_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/oasis_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/oasis_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

levelshots/radar_cc_automap
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/radar_cc.tga
		depthFunc equal
		rgbGen identity
	}
}

levelshots/radar_cc_trans
{
	nopicmip
	nocompress
	nomipmaps
	{
		clampmap levelshots/radar_cc.tga
		blendfunc blend
		rgbGen identity
		alphaGen vertex
	}
}

