// lights.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 63 total shaders

textures/lights/light_c01
{
	qer_editorimage textures/lights/light_c01.tga
	q3map_lightimage textures/lights/light_c01.blend.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c01.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c01_2k
{
	qer_editorimage textures/lights/light_c01.tga
	q3map_lightimage textures/lights/light_c01.blend.tga
	q3map_surfacelight 2000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c01.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c01_8k
{
	qer_editorimage textures/lights/light_c01.tga
	q3map_lightimage textures/lights/light_c01.blend.tga
	q3map_surfacelight 8000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c01.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c01_10k
{
	qer_editorimage textures/lights/light_c01.tga
	q3map_lightimage textures/lights/light_c01.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c01.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c01_10k_noblock
{
	qer_editorimage textures/lights/light_c01.tga
	q3map_lightimage textures/lights/light_c01.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c01.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c02
{
	qer_editorimage textures/lights/light_c02.tga
	q3map_lightimage textures/lights/light_c02.blend.tga
	q3map_surfacelight 2500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c02.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c02_10000
{
	qer_editorimage textures/lights/light_c02.tga
	q3map_lightimage textures/lights/light_c02.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c02.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c02_20000
{
	qer_editorimage textures/lights/light_c02.tga
	q3map_lightimage textures/lights/light_c02.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c02.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c04
{
	qer_editorimage textures/lights/light_c04.tga
	q3map_lightimage textures/lights/light_c04.blend.tga
	q3map_surfacelight 2500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c04.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c04_nolight
{
	qer_editorimage textures/lights/light_c04.tga
	q3map_lightimage textures/lights/light_c04.blend.tga
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c04.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c04_10000
{
	qer_editorimage textures/lights/light_c04.tga
	q3map_lightimage textures/lights/light_c04.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c04.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c04_20000
{
	qer_editorimage textures/lights/light_c04.tga
	q3map_lightimage textures/lights/light_c04.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c04.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c06
{
	qer_editorimage textures/lights/light_c06.tga
	q3map_lightimage textures/lights/light_c06.blend.tga
	q3map_surfacelight 2500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c06.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c06.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c06_10000
{
	qer_editorimage textures/lights/light_c06.tga
	q3map_lightimage textures/lights/light_c06.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c06.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c06.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c06_20000
{
	qer_editorimage textures/lights/light_c06.tga
	q3map_lightimage textures/lights/light_c06.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c06.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c06.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_c06_25000
{
	qer_editorimage textures/lights/light_c06.tga
	q3map_lightimage textures/lights/light_c06.blend.tga
	q3map_surfacelight 25000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_c06.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_c06.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m1r
{
	qer_editorimage textures/lights/light_m1r.tga
	nofog
	surfaceparm nomarks
	surfaceparm pointlight
	{
		animMap 1 textures/lights/light_m1r.tga textures/lights/light_m2r.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
}

textures/lights/light_m4
{
	qer_editorimage textures/lights/light_m4.tga
	q3map_lightimage textures/lights/light_m4.blend.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m4.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m4_white
{
	qer_editorimage textures/lights/light_m4.tga
	q3map_lightimage textures/lights/light_m4.blend.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m4.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m5_red
{
	qer_editorimage textures/lights/light_m5.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m5.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m5_red20k
{
	qer_editorimage textures/lights/light_m5.tga
	q3map_surfacelight 20000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m5.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m6_bwhite
{
	qer_editorimage textures/lights/light_m6.tga
	q3map_lightimage textures/lights/light_m6.blend.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m6.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m6_100
{
	qer_editorimage textures/lights/light_m6.tga
	q3map_lightimage textures/lights/light_m6.blend.tga
	q3map_surfacelight 100
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m6.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m11_max
{
	qer_editorimage textures/lights/light_m11.tga
	q3map_lightimage textures/lights/test.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m11.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m11.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m11_red
{
	qer_editorimage textures/lights/light_m11.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m11.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m11.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m11_red_2500
{
	qer_editorimage textures/lights/light_m11.tga
	q3map_surfacelight 2500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m11.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m11.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m15_small
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m16_small
{
	qer_editorimage textures/lights/light_m16.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m16.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m16_5k
{
	qer_editorimage textures/lights/light_m16.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m16.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m16_10k
{
	qer_editorimage textures/lights/light_m16.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m16.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m16_15k
{
	qer_editorimage textures/lights/light_m16.tga
	q3map_surfacelight 15000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m16.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m16_20k
{
	qer_editorimage textures/lights/light_m16.tga
	q3map_surfacelight 20000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m16.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m20_fb
{
	qer_editorimage textures/lights/light_m20.tga
	q3map_surfacesurfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m20.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m20.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m20_5000
{
	qer_editorimage textures/lights/light_m20.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
}

textures/lights/light_m21_fb
{
	qer_editorimage textures/lights/light_m21.tga
	q3map_surfacesurfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m20.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m20.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m21_5000
{
	qer_editorimage textures/lights/light_m21.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m21.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m21.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m25b
{
	qer_editorimage textures/lights/light_m25b.tga
	q3map_lightimage textures/lights/light_msb1.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 8000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m25b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m25b.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m25b_2k
{
	qer_editorimage textures/lights/light_m25b.tga
	q3map_lightimage textures/lights/light_msb1.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 2000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m25b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m25b.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m25blue
{
	qer_editorimage textures/lights/light_m25blue.tga
	q3map_lightimage textures/lights/light_m25blue.tga
	q3map_surfacelight 8000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m25blue.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m25blue.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m25r
{
	qer_editorimage textures/lights/light_m25r.tga
	q3map_lightimage textures/lights/light_m25r.tga
	q3map_surfacelight 8000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m25r.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m25r.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m30
{
	qer_editorimage textures/lights/light_m30.tga
	q3map_lightimage textures/lights/light_m30.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m30.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m30.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_m30r
{
	qer_editorimage textures/lights/light_m30r.tga
	q3map_lightimage textures/lights/light_m30r.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m30r.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m30r.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_sd1
{
	q3map_lightimage textures/lights/light_m4.blend.tga
	q3map_surfacelight 5000
	polygonOffset
	{
		map textures/lights/light_sd1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen const ( 0.5 0.5 0.5 )
	}
}

textures/lights/light_tp_m05
{
	qer_editorimage textures/lights/light_tp_m05.tga
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m05.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m2.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_tp_m06
{
	qer_editorimage textures/lights/light_tp_m06.tga
	q3map_surfacelight 6000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m06.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m2.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_tp_m07
{
	qer_editorimage textures/lights/light_tp_m07.tga
	q3map_surfacelight 6000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m07.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m2.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_tp_m08
{
	qer_editorimage textures/lights/light_tp_m08.tga
	q3map_surfacelight 6000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m08.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_tp_m2.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_03_2500
{
	qer_editorimage textures/lights/light_xlight_03.tga
	q3map_surfacelight 2500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_03.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_03.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_700
{
	qer_editorimage textures/lights/light_xlight_02.tga
	q3map_surfacelight 700
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_750
{
	qer_editorimage textures/lights/light_xlight_01.tga
	q3map_surfacelight 750
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_01.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_1500
{
	qer_editorimage textures/lights/light_xlight_02.tga
	q3map_surfacelight 1500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_2500
{
	qer_editorimage textures/lights/light_xlight_02.tga
	q3map_surfacelight 2500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_4000
{
	qer_editorimage textures/lights/light_xlight_02.tga
	q3map_surfacelight 4000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight_5500
{
	qer_editorimage textures/lights/light_xlight_02.tga
	q3map_surfacelight 5500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight3_4000
{
	qer_editorimage textures/lights/light_xlight_03.tga
	q3map_surfacelight 4000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/light_xlight3_5500
{
	qer_editorimage textures/lights/light_xlight_03.tga
	q3map_surfacelight 5500
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_xlight_02.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_5k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 5000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_6k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 6000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_7k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 7000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_8k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 8000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_9k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 9000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_10k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 10000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}

textures/lights/mlight_30k
{
	qer_editorimage textures/lights/light_m15.tga
	q3map_lightimage textures/lights/light_m15.blend.tga
	q3map_surfacelight 30000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/lights/light_m15.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/lights/light_m15.blend.tga
		blendFunc GL_ONE GL_ONE
	}
}
