// miltary_wall.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 5 total shaders

textures/miltary_wall/brick_l_01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/miltary_wall/miltary_m01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/miltary_wall/miltary_m06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/miltary_wall/miltary_m06_cloth
{
	implicitMap textures/miltary_wall/miltary_m06.tga
}

textures/miltary_wall/mroof_m01a
{
	surfaceparm roofsteps
	implicitMap -
}

textures/miltary_wall/window_m03
{
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm pointlight
	implicitBlend -
}
