// miltary_door.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

textures/miltary_door/mdoor_c03
{
	surfaceparm metalsteps
	implicitMap -
}

textures/miltary_door/mdoor_c04
{
	surfaceparm metalsteps
	implicitMap -
}

textures/miltary_door/mdoor_m01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/miltary_door/mdoor_m01b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/miltary_door/mdoor_m08a
{
	surfaceparm metalsteps
	implicitMap -
}
