// models_furniture.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

models/furniture/barrel/barrel_m01
{
	{
		map textures/effects/tinfx.tga
		rgbGen lightingDiffuse
		tcGen environment
	}
	{
		map models/furniture/barrel/barrel_m01.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen lightingDiffuse
	}
}
