// models_ammo.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 2 total shaders

models/ammo/rocket/rockflar
{
	cull disable
	{
		map models/ammo/rocket/rockflar
		blendfunc GL_ONE GL_ONE
	}
}

models/ammo/rocket/rockfls2
{
	cull disable
	{
		map models/ammo/rocket/rockfls2
		blendfunc GL_ONE GL_ONE
	}
}

models/ammo/grenade
{
	diffuseMap		models/weapons2/grenade/grenade_yd
	specularMap		models/weapons2/grenade/grenade_yd
	normalMap		_flat
}
