// models_shards.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

models/shards/glass
{
	qer_editorimage models/shards/glass.tga
	qer_trans 0.5
	cull none
	surfaceparm trans
	{
		map textures/effects/wdfx4.tga
		blendFunc GL_ONE GL_ONE
		rgbGen identity
		tcgen environment
	}
}
