// models_weapons2.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 16 total shaders
models/weapons2/arms/arm_allied
{
	diffuseMap		models/weapons2/arms/arm_allied
	specularMap		models/weapons2/arms/arm_allied
	normalMap		heightMap(models/weapons2/arms/arm_allied, 1)
}

models/weapons2/arms/arm_axis
{
	diffuseMap		models/weapons2/arms/arm_axis
	specularMap		models/weapons2/arms/arm_axis
	normalMap		heightMap(models/weapons2/arms/arm_axis, 1)
}

models/weapons2/c4_dynamite/dynomite1a
{
	diffuseMap		models/weapons2/c4_dynamite/dynomite1a
	specularMap		models/weapons2/c4_dynamite/dynomite1a
	normalMap		heightMap(models/weapons2/c4_dynamite/dynomite1a, 1)
}

models/weapons2/grenade/grenade_us
{
	diffuseMap		models/weapons2/grenade/grenade_us
	specularMap		models/weapons2/grenade/grenade_us
	normalMap		heightMap(models/weapons2/grenade/grenade_us, 1)
}


models/weapons2/colt/colt4
{
	diffuseMap		models/weapons2/colt/colt_yd
	specularMap		models/weapons2/colt/colt_yd
	normalMap		heightMap(models/weapons2/colt/colt_yd, 1)
}

models/weapons2/fg42/fg42_2
{
	diffuseMap		models/weapons2/fg42/fg42_yd
	specularMap		models/weapons2/fg42/fg42_yd
	normalMap		heightMap(models/weapons2/fg42/fg42_yd, 1)
}

models/weapons2/flamethrower/flame1
{
	diffuseMap		models/weapons2/flamethrower/flame1_yd
	specularMap		models/weapons2/flamethrower/flame1_yd
	normalMap		heightMap(models/weapons2/flamethrower/flame1_yd, 1)
}

models/weapons2/grenade/grenade
{
	diffuseMap		models/weapons2/grenade/grenade_yd
	specularMap		models/weapons2/grenade/grenade_yd
	normalMap		heightMap(models/weapons2/grenade/grenade_yd, 1)
}

models/weapons2/knife/knife1a
{
	diffuseMap		models/weapons2/knife/knife_yd
	specularMap		models/weapons2/knife/knife_yd
	normalMap		heightMap(models/weapons2/knife/knife_yd, 1)
}

models/weapons2/lightning/f_lightning
{
	cull disable
	sort additive
	{
		map models/weapons2/flamethrower/flash
		blendfunc GL_ONE GL_ONE
	}
}

models/weapons2/luger/luger7
{
	diffuseMap		models/weapons2/luger/luger7_yd
	specularMap		models/weapons2/luger/luger7_yd
	normalMap		heightMap(models/weapons2/luger/luger7_yd, 1)
}

models/weapons2/luger/silncer
{
	diffuseMap		models/weapons2/luger/silncer
	specularMap		models/weapons2/luger/silncer
	normalMap		heightMap(models/weapons2/luger/silncer, 1)
}

models/weapons2/machinegun/f_machinegun
{
	cull disable
	nofog
	sort additive
	{
		animMap 2 models/weapons2/machinegun/f_machinegun models/weapons2/machinegun/f_machinegun1
		blendfunc GL_ONE GL_ONE
	}
}

models/weapons2/mauser/mauser3
{
	diffuseMap		models/weapons2/mauser/mauser3_yd
	specularMap		models/weapons2/mauser/mauser3_yd
	normalMap		heightMap(models/weapons2/mauser/mauser3_yd, 1)
}

models/weapons2/mauserif5
{
	diffuseMap		models/weapons2/mauserif5
	specularMap		models/weapons2/mauserif5
	normalMap		heightMap(models/weapons2/mauserif5, 1)
}

models/weapons2/mp40/gun11
{
	diffuseMap		models/weapons2/mp40/gun11_yd
	specularMap		models/weapons2/mp40/gun11_yd
	normalMap		heightMap(models/weapons2/mp40/gun11_yd, 1)
}

models/weapons2/mp40/hand16
{
	diffuseMap		models/weapons2/mp40/hand16
	specularMap		models/weapons2/mp40/hand16
	normalMap		heightMap(models/weapons2/mp40/hand16, 1)
}

models/weapons2/rocketl/f_rocketl
{
	cull disable
	sort additive
	{
		map models/weapons2/rocketl/f_rocketl
		blendfunc GL_ONE GL_ONE
	}
}

models/weapons2/shells/M_shell
{
	diffuseMap		models/weapons2/shells/M_shell
	specularMap		models/weapons2/shells/M_shell
	normalMap		heightMap(models/weapons2/shells/M_shell, 1)
}

models/weapons2/rocketl/panzerfast1a
{
	diffuseMap		models/weapons2/panzerfaust/panzerfaust_yd
	specularMap		models/weapons2/panzerfaust/panzerfaust_yd
	normalMap		heightMap(models/weapons2/panzerfaust/panzerfaust_yd, 1)
}

models/weapons2/rocketl/rocketl14
{
	cull disable
	sort additive
	{
		map models/weapons2/rocketl/f_rocketl
		blendfunc GL_ONE GL_ONE
	}
}

models/weapons2/sten/sten1
{
	diffuseMap		models/weapons2/sten/sten1_yd
	specularMap		models/weapons2/sten/sten1_yd
	normalMap		heightMap(models/weapons2/sten/sten1_yd, 1)
}

models/weapons2/thompson/thompson_la
{
	diffuseMap		models/weapons2/thompson/thompson_la_yd
	specularMap		models/weapons2/thompson/thompson_la_yd
	normalMap		heightMap(models/weapons2/thompson/thompson_la_yd, 1)
}

models/weapons2/venom/venum1
{
	diffuseMap		models/weapons2/venom/venum1aa
	specularMap		models/weapons2/venom/venum1aa
	normalMap		heightMap(models/weapons2/venom/venum1aa, 1)
}
