// models_foliage.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 9 total shaders

models/foliage/clover_1
{
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/clover_1.tga
	cull disable
	distanceCull 256 1024 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map models/foliage/clover_1.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/fern
{
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/fern.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 256 4096 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map models/foliage/fern.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/grass_dense
{
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/grass_tan.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 128 2048 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map models/foliage/grass_tan.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/grass_1
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/grass_1.tga
	cull disable
	distanceCull 256 4096 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	{
		map models/foliage/grass_1.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/grass_5
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/grass_tan.tga
	cull disable
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 256 4096 0.49
	{
		map models/foliage/grass_tan.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/leaf1
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/leaf1.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 256 4096 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	{
		map models/foliage/leaf1.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/plant_a
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/plant_a.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 512 3192 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	{
		map models/foliage/plant_a.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/thick_a
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/thick_a.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 512 3192 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	{
		map models/foliage/thick_a.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/thick_brush
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/brush_brown.tga
	cull disable
	distanceCull 256 1536 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	{
		map models/foliage/brush_brown.tga
		//blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/grassfoliage1
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/grassfoliage1.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 512 1792 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map models/foliage/grassfoliage1.tga
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/grassfoliage2
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/grassfoliage2.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 512 1536 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map models/foliage/grassfoliage2.tga
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/grassfoliage3
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage models/foliage/grassfoliage3.tga
	cull disable
	// distanceCull <inner> <outer> <alpha threshold>
	distanceCull 480 1280 0.49
	sort seethrough
	surfaceparm pointlight
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map models/foliage/grassfoliage3.tga
		alphaFunc GE128
		rgbGen exactVertex
		alphaGen vertex
	}
}

models/foliage/raincircle0
{
	qer_alphafunc greater 0.5
	qer_editorimage sprites/wake.tga
	distanceCull 480 1024 0.49
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	nomipmaps
	
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth		0 1 0 1.5
		alphaGen wave inversesawtooth	0 1 0 1.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth		0 1 0 1.5
		alphaGen wave inversesawtooth	0 1 0 1.5
	}
}

models/foliage/raincircle1
{
	nopicmip
	qer_alphafunc greater 0.5
	qer_editorimage sprites/wake.tga
	distanceCull 480 1024 0.49
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	nomipmaps
	
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.33 1.5
		alphaGen wave inversesawtooth	0 1 0.33 1.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.33 1.5
		alphaGen wave inversesawtooth	0 1 0.33 1.5
	}
}

models/foliage/raincircle2
{
	qer_alphafunc greater 0.5
	qer_editorimage sprites/wake.tga
	distanceCull 384 768 0.49
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	nomipmaps
	
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.66 1.5
		alphaGen wave inversesawtooth	0 1 0.66 1.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.66 1.5
		alphaGen wave inversesawtooth	0 1 0.66 1.5
	}
}

models/foliage/raincircle3
{
	qer_alphafunc greater 0.5
	qer_editorimage sprites/wake.tga
	distanceCull 384 768 0.49
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	nomipmaps
	
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.25 1.5
		alphaGen wave inversesawtooth	0 1 0.25 1.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.25 1.5
		alphaGen wave inversesawtooth	0 1 0.25 1.5
	}
}


models/foliage/raincircle4
{
	qer_alphafunc greater 0.5
	qer_editorimage sprites/wake.tga
	distanceCull 256 512 0.49
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	nomipmaps
	
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.75 1.5
		alphaGen wave inversesawtooth	0 1 0.75 1.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.75 1.5
		alphaGen wave inversesawtooth	0 1 0.75 1.5
	}
}

models/foliage/raincircle5
{
	qer_alphafunc greater 0.5
	qer_editorimage sprites/wake.tga
	distanceCull 256 512 0.49
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	nomipmaps
	
	{
		clampmap sprites/wake.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		tcMod stretch sawtooth			0 1 0.75 1.5
		alphaGen wave inversesawtooth	0 1 0.75 1.5
	}
	{
		clampmap sprites/wake.tga
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_ALPHA
		tcMod transform -1 0 0 -1 1 1
		tcMod stretch sawtooth			0 1 0.5 1.5
		alphaGen wave inversesawtooth	0 1 0.75 1.5
	}
}
