// mp_guns.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 12 total shaders

textures/mp_guns/mp_guns_sky
{
	qer_editorimage textures/skies/newclouds
	q3map_globaltexture
	q3map_lightsubdivide 512
	q3map_surfacelight 85
	fogvars ( .6 .6 .6 ) 5400
	skyfogvars ( .23 .23 .24 ) .005
	skyparms - 200 -
	surfaceparm nodlight
	surfaceparm nolightmap
	surfaceparm sky
	{
		map textures/skies/dimclouds
		tcMod scroll 0.002 0.002
		tcMod scale 1 1
		tcMod turb 0 0.05 0 .08
	}
	{
		map textures/skies/dimclouds
		blendfunc GL_ONE GL_ONE
		tcMod scroll -0.001 -0.005
		tcMod scale 10 10
	}
}

textures/mp_guns/terrain_0
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/ground_c09a.jpg
		rgbGen vertex
		tcmod scale 0.041666667 0.041666667
	}
}

textures/mp_guns/terrain_0to1
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/ground_c09a.jpg
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.041666667 0.041666667
	}
	{
		map textures/stone/dirt_m03.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.083333333 0.083333333
	}
}

textures/mp_guns/terrain_0to2
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/ground_c09a.jpg
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.041666667 0.041666667
	}
	{
		map textures/xp_88mm/mud
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.083333333 0.083333333
	}
}

textures/mp_guns/terrain_0to3
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/ground_c09a.jpg
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.041666667 0.041666667
	}
	{
		map textures/stone/mxrock3_a.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.041666667 0.041666667
	}
}

textures/mp_guns/terrain_0to4
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/ground_c09a.jpg
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.041666667 0.041666667
	}
	{
		map textures/xp_88mm/blasted_earth
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.166666666 0.166666666
	}
}

textures/mp_guns/terrain_1
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/dirt_m03.jpg
		rgbGen vertex
		tcmod scale 0.083333333 0.083333333
	}
}

textures/mp_guns/terrain_1to2
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/dirt_m03.jpg
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.083333333 0.083333333
	}
	{
		map textures/xp_88mm/mud
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.083333333 0.083333333
	}
}

textures/mp_guns/terrain_1to3
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/dirt_m03.jpg
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.083333333 0.083333333
	}
	{
		map textures/stone/mxrock3_a.jpg
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
		alphaGen vertex
		tcmod scale 0.041666667 0.041666667
	}
}

textures/mp_guns/terrain_2
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/xp_88mm/mud
		rgbGen vertex
		tcmod scale 0.083333333 0.083333333
	}
}

textures/mp_guns/terrain_3
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/stone/mxrock3_a.jpg
		rgbGen vertex
		tcmod scale 0.041666667 0.041666667
	}
}

textures/mp_guns/terrain_4
{
	q3map_forcesunlight
	q3map_novertexshadows
	surfaceparm nolightmap
	{
		map textures/xp_88mm/blasted_earth
		rgbGen vertex
		tcmod scale 0.166666666 0.166666666
	}
}
