// mp_rocket.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/mp_rocket/fence_c10_light
{
	qer_editorimage textures/alpha/fence_c10_light
	cull disable
	nomipmaps
	nopicmip
	surfaceparm alphashadow
	surfaceparm metalsteps
	surfaceparm nomarks
	surfaceparm pointlight
	implicitMask textures/alpha/fence_c10_light
}
