// railway_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 16 total shaders

textures/railway_sd/d_cross
{
	polygonOffset
	surfaceparm pointlight
	{
		map textures/railway_sd/d_cross.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen const ( 0.7 0.7 0.7 )
	}
}

textures/railway_sd/d_label01
{
	polygonOffset
	surfaceparm pointlight
	{
		map textures/railway_sd/d_label01.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen const ( 0.7 0.7 0.7 )
	}
}

textures/railway_sd/d_label02
{
	polygonOffset
	surfaceparm pointlight
	{
		map textures/railway_sd/d_label02.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen const ( 0.7 0.7 0.7 )
	}
}

textures/railway_sd/d_skull
{
	polygonOffset
	surfaceparm pointlight
	{
		map textures/railway_sd/d_skull.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen const ( 0.7 0.7 0.7 )
	}
}

textures/railway_sd/metaltrim_a
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/metalwall_a
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/metalwall_b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/metalwall_c
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/panel_trim001
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/panel_001a
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/panel_001b
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/panel_001c
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/panel_001d
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/panel_001e
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/support001
{
	surfaceparm metalsteps
	implicitMap -
}

textures/railway_sd/support003
{
	surfaceparm metalsteps
	implicitMap -
}
