// siwa_props_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 3 total shaders

textures/siwa_props_sd/siwa_carpet2
{
	qer_editorimage textures/siwa_props_sd/siwa_carpet2.tga
	cull disable
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm pointlight
	surfaceparm trans
	{
		map textures/siwa_props_sd/siwa_carpet2.tga
		blendfunc blend
		rgbGen Vertex
	}
}

textures/siwa_props_sd/siwa_carpet4
{
	qer_editorimage textures/siwa_props_sd/siwa_carpet4.tga
	cull disable
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm pointlight
	surfaceparm trans
	{
		map textures/siwa_props_sd/siwa_carpet4.tga
		blendfunc blend
		rgbGen Vertex
	}
}

textures/siwa_props_sd/siwa_carpet5
{
	qer_editorimage textures/siwa_props_sd/siwa_carpet5.tga
	cull disable
	surfaceparm alphashadow
	surfaceparm nonsolid
	surfaceparm pointlight
	surfaceparm trans
	{
		map textures/siwa_props_sd/siwa_carpet5.tga
		blendfunc blend
		rgbGen Vertex
	}
}
