// siwa_fx_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/siwa_fx_sd/siwa_waternodraw
{
	qer_editorimage textures/siwa_fx_sd/siwa_waterfx2.tga
	qer_trans 0.25
	surfaceparm nodraw
	surfaceparm water
}
