// stone.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/stone/mxdebri0_riverbed
{

	qer_editorimage textures/stone/mxdebri0_riverbed
	diffusemap		textures/stone/mxdebri0_riverbed
	bumpmap         displacemap( textures/stone/mxdebri0_riverbed_norm, invertColor(stone/mxdebri0_riverbed_disp) )
	specularmap		textures/stone/mxdebri0_riverbed_spec
	
}

textures/stone/mxrock1aa
{
	surfaceparm grasssteps
	implicitMap -
	
	er_editorimage textures/stone/mxrock1aa
	diffusemap		textures/stone/mxrock1aa
	bumpmap         displacemap( textures/stone/mxrock1aa_norm, invertColor(stone/mxrock1aa_disp) )
	specularmap		textures/stone/mxrock1aa_spec
	
	
}

textures/stone/mxrock3_a
{

	qer_editorimage textures/stone/mxrock3_a
	diffusemap		textures/stone/mxrock3_a
	bumpmap         displacemap( textures/stone/mxrock3_a_norm, invertColor(stone/mxrock3_a_disp) )
	specularmap		textures/stone/mxrock3_a_spec
	
}

textures/stone/mxrock3h_snow
{

	qer_editorimage textures/stone/mxrock3h_snow
	diffusemap		textures/stone/mxrock3h_snow
	bumpmap         displacemap( textures/stone/mxrock3h_snow_norm, invertColor(stone/mxrock3h_snow_disp) )
	specularmap		textures/stone/mxrock3h_snow_spec
	
}

textures/stone/mxsnow2
{

	qer_editorimage textures/stone/mxsnow2
	diffusemap		textures/stone/mxsnow2
	bumpmap         displacemap( textures/stone/mxsnow2_norm, invertColor(stone/mxsnow2_disp) )
	specularmap		textures/stone/mxsnow2_spec
	
}

textures/stone/mxsnow3
{

	qer_editorimage textures/stone/mxsnow3
	diffusemap		textures/stone/mxsnow3
	bumpmap         displacemap( textures/stone/mxsnow3_norm, invertColor(stone/mxsnow3_disp) )
	specularmap		textures/stone/mxsnow3_spec
	
}