// terrain.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 4 total shaders

textures/terrain/grass_dm01
{
	surfaceparm grasssteps
	implicitMap -
}

textures/terrain/grass_dm01_phong
{
	qer_editorimage textures/terrain/grass_dm01.tga
	q3map_nonplanar
	q3map_shadeangle 120
	surfaceparm grasssteps
	implicitMap textures/terrain/grass_dm01.tga
}

textures/terrain/grass_dm01_wils
{
	qer_editorimage textures/terrain/grass_dm01.tga
	q3map_nonplanar
	q3map_shadeangle 120
	surfaceparm grasssteps
	implicitMap textures/terrain/grass_dm01.tga
}

textures/terrain/grass_trainwreck
{
	qer_editorimage textures/terrain/grass_dm01.tga
	q3map_nonplanar
	q3map_shadeangle 120
	surfaceparm grasssteps
	implicitMap textures/terrain/grass_dm01.tga
}
