// town_wall.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 3 total shaders

textures/town_wall/store_c01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wall/store_c02
{
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wall/store_c03_a
{
	surfaceparm woodsteps
	implicitMap -
}
