// town_wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 4 total shaders

textures/town_wood/trenchwood
{
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wood/wood_c01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wood/wood_c02
{
	surfaceparm woodsteps
	implicitMap -
}

textures/town_wood/wood_c11
{
	surfaceparm woodsteps
	implicitMap -
}
