// tree.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 6 total shaders

textures/tree/tree_m02dm
{
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/tree_m02s
{
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/tree_m07_lod
{
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/tree_m08
{
	nopicmip
	cull twosided
	surfaceparm alphashadow
	surfaceparm nomarks
	surfaceparm trans
	implicitMask -
}

textures/tree/trunck3
{
	cull twosided
	surfaceparm nomarks
	{
		map textures/tree/trunck3.tga
		rgbGen identity
	}
}

textures/tree/trunck3a
{
	cull twosided
	surfaceparm nomarks
	{
		map textures/tree/trunck3a.tga
		rgbGen identity
	}
}
