// ui_assets2.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 3 total shaders

ui/assets2/mapsheet_blend
{
	nomipmaps
	nopicmip
	{
		clampmap ui/assets2/mapsheet.tga
		blendfunc blend
		alphagen vertex
	}
}

ui/assets2/maptrim_long
{
	nomipmaps
	nopicmip
	{
		map ui/assets2/maptrim_long.tga
	}
}

ui/assets2/maptrim_long2
{
	nomipmaps
	nopicmip
	{
		map ui/assets2/maptrim_long2.tga
	}
}
