// villa_sd.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 1 total shaders

textures/villa_sd/villawindow_a
{
	surfaceparm alphashadow
	surfaceparm glass
	surfaceparm pointlight
	surfaceparm trans
	{
		map textures/villa_sd/villawindow_a.tga
		blendfunc GL_ONE GL_ONE
		rgbGen vertex
	}
	{
		map textures/villa_sd/villawindow_a.tga
		alphaFunc GE128
		rgbGen vertex
	}
}
