// wood.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 26 total shaders

textures/wood/wood_c01
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m01_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m02
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m02a
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05_usata
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usat_snow
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usata
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m05a_usata_dm
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06a
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m06b
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m08
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m08_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m09
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m09_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m11
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m12a
{
	qer_editorimage textures/wood/wood_m12.tga
	surfaceparm woodsteps
	implicitMap textures/wood/wood_m12.tga
}

textures/wood/wood_m13
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m13_usat
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m16
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m16cm
{
	surfaceparm woodsteps
	implicitMap -
}

textures/wood/wood_m18
{
	surfaceparm woodsteps
	implicitMap -
}
