// xlab_wall.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 10 total shaders

textures/xlab_wall/x_metalwall_m01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xmetal_c03
{
	surfaceparm metalsteps
	implicitMap -
}

//===========================================================================
// Metal phong for the brushwork only railings in fueldump
//===========================================================================
textures/xlab_wall/xmetal_c03_phong
{
	surfaceparm metalsteps
	q3map_nonplanar
	q3map_shadeangle 179
	qer_editorimage textures/xlab_wall/xmetal_c03_phong.tga
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/xlab_wall/xmetal_c03.tga
		blendFunc filter
	}
}

textures/xlab_wall/xmetal_m02
{
	surfaceparm metalsteps
	{
		map textures/effects/tinfx.tga
		rgbGen identity
		tcGen environment
	}
	{
		map textures/xlab_wall/xmetal_m02.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/xlab_wall/xmetal_m02a
{
	surfaceparm metalsteps
	{
		map textures/effects/tinfx.tga
		rgbGen identity
		tcGen environment
	}
	{
		map textures/xlab_wall/xmetal_m02a.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/xlab_wall/xmetal_m02a_trim
{
	surfaceparm metalsteps
	{
		map textures/effects/tinfx.tga
		rgbGen identity
		tcGen environment
	}
	{
		map textures/xlab_wall/xmetal_m02a_trim.tga
		blendFunc GL_ONE GL_ONE_MINUS_SRC_ALPHA
		rgbGen identity
	}
	{
		map $lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

textures/xlab_wall/xmetal_m02f
{
	qer_editorimage textures/xlab_wall/xmetal_m02.tga
	surfaceparm metalsteps
	implicitMap textures/xlab_wall/xmetal_m02.tga
}

textures/xlab_wall/xmetal_m03l
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c02
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c04
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c05
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c06
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xtrim_c07
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_wall/xwall_c07
{
	surfaceparm metalsteps
	implicitMap -
}
