// xlab_props.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 8 total shaders

textures/xlab_props/panel_m01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_props/panel_m01_light
{
	qer_editorimage textures/xlab_props/panel_m01.tga
	q3map_lightimage textures/xlab_props/softblue.tga
	q3map_lightsubdivide 128
	q3map_surfacelight 1000
	surfaceparm nomarks
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/xlab_props/panel_m01.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen wave sin 1 .1 0 7
	}
}

textures/xlab_props/xdrawers_c03
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_props/xgrid_c01
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_props/xpanel_c02dm
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_props/xpanel_c05_light_half
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_props/xpanel_c08
{
	surfaceparm metalsteps
	implicitMap -
}

textures/xlab_props/xpanel_c10_light
{
	surfaceparm metalsteps
	implicitMap -
}
