FIND_PATH( SPEEXDSP_INCLUDE_DIR NAMES speex/speex_preprocess.h )
MARK_AS_ADVANCED( SPEEXDSP_INCLUDE_DIR )

FIND_PATH( SPEEX_INCLUDE_DIR NAMES speex/speex.h )
MARK_AS_ADVANCED( SPEEX_INCLUDE_DIR)

FIND_LIBRARY( SPEEXDSP_LIBRARY NAMES speexdsp )
MARK_AS_ADVANCED( SPEEXDSP_LIBRARY )

FIND_LIBRARY( SPEEX_LIBRARY NAMES speex )
MARK_AS_ADVANCED( SPEEX_LIBRARY )

INCLUDE( ${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( Speex DEFAULT_MSG SPEEX_LIBRARY SPEEX_INCLUDE_DIR SPEEXDSP_LIBRARY SPEEXDSP_INCLUDE_DIR )

SET( SPEEX_LIBRARIES ${SPEEXDSP_LIBRARY} ${SPEEX_LIBRARY} )
SET( SPEEX_INCLUDE_DIRS ${SPEEXDSP_INCLUDE_DIR} ${SPEEX_INCLUDE_DIR} )
