FIND_PATH( NETTLE_INCLUDE_DIR NAMES nettle/rsa.h )
MARK_AS_ADVANCED( NETTLE_INCLUDE_DIR)

FIND_LIBRARY( NETTLE_LIBRARY NAMES nettle )
MARK_AS_ADVANCED( NETTLE_LIBRARY )

FIND_LIBRARY( HOGWEED_LIBRARY NAMES hogweed )
MARK_AS_ADVANCED( HOGWEED_LIBRARY )

INCLUDE( ${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( Nettle DEFAULT_MSG NETTLE_LIBRARY HOGWEED_LIBRARY NETTLE_INCLUDE_DIR )

SET( NETTLE_LIBRARIES ${NETTLE_LIBRARY} ${HOGWEED_LIBRARY} )
SET( NETTLE_INCLUDE_DIRS ${NETTLE_INCLUDE_DIR} )
