@echo off
REM This file specifies common cmake arguments between 32 bit and 64 bit Visual Studio builds

set args=-DUSE_INTERNAL_JPEG=ON -DUSE_INTERNAL_SDL=ON -DUSE_INTERNAL_CRYPTO=ON -DUSE_INTERNAL_SPEEX=ON -DUSE_INTERNAL_GLEW=ON -DUSE_CURSES=OFF -DUSE_GLSL_OPTIMIZER=OFF -DBUILD_DAEMONMAP=ON -DUSE_CIN_XVID=OFF -DENABLE_HARDENING=OFF -DENABLE_WARNINGS=OFF -DCMAKE_CONFIGURATION_TYPES=Release;Debug