#! /bin/sh

test -f ~/.unvanquished/config/autogen.cfg && exit 0
test -f ~/.Unvanquished/main/profiles/defaultprofile.dat || exit 0

set -e

NAME="$(cat ~/.Unvanquished/main/profiles/defaultprofile.dat)"

mkdir -p ~/.unvanquished/config

cp -a ~/.Unvanquished/main/profiles/"$NAME"/pubkey 			~/.unvanquished/
cp -a ~/.Unvanquished/main/profiles/"$NAME"/keybindings.cfg		~/.unvanquished/config/
grep '^seta name ' ~/.Unvanquished/main/profiles/"$NAME"/autogen.cfg	>~/.unvanquished/config/autogen.cfg

echo "Basic profile for '$NAME' has been copied into ~/.unvanquished."
echo 'Most settings have not been transferred.'
