#! /bin/sh

test -f ~/.Unvanquished/main/profiles/defaultprofile.dat && exit 0
test -f ~/.Unvanquished/main/autogen.cfg || exit 0

set -e

# need this to avoid case folding
export LANG=C

NAME="$(sed -e '/^seta name /! d; s/^seta name //; s/\^[0-:<-o]//g; s/[^0-9A-Za-z]//g; q' ~/.Unvanquished/main/autogen.cfg)"
mkdir -p ~/.Unvanquished/main/profiles/"$NAME"
cp -al ~/.Unvanquished/pubkey \
       ~/.Unvanquished/main/guid \
       ~/.Unvanquished/main/*.cfg ~/.Unvanquished/main/profiles/"$NAME"/
echo "$NAME" >~/.Unvanquished/main/profiles/"$NAME"/profile.dat
echo "$NAME" >~/.Unvanquished/main/profiles/defaultprofile.dat

echo "Default profile created for '$NAME'."
