#! /bin/sh
cd /var/games/unvanquished-server

case "$1" in
-h|-help|--help)
  exec /usr/lib/games/unvanquished/unvanquishedded --help
  ;;
esac

exec /usr/lib/games/unvanquished/unvanquishedded -libpath /usr/lib/games/unvanquished -pakpath /var/games/unvanquished/pkg "$@" +exec server.cfg
