#! /bin/sh

set -e

test -f ~/.unvanquished/pubkey && chmod go= ~/.unvanquished/pubkey

test "$1" != --force -a -f ~/.unvanquished/config/autogen.cfg && exit 0
test -f ~/.Unvanquished/main/profiles/defaultprofile.dat || exit 0
NAME="$(cat ~/.Unvanquished/main/profiles/defaultprofile.dat)"
test -d ~/.Unvanquished/main/profiles/"$NAME" || exit 0

mkdir -p ~/.unvanquished/config ~/.unvanquished/game ~/.unvanquished/pkg

cd ~/.Unvanquished/main
for UNV_FILE in default.cfg server.cfg configs scripts; do
  test -e "$UNV_FILE" && cp -alu "$UNV_FILE" ~/.unvanquished/config/
done
for UNV_FILE in maprotation.cfg layouts; do
  test -e "$UNV_FILE" && cp -alu "$UNV_FILE" ~/.unvanquished/game/
done

cd ~/.Unvanquished/main/profiles/"$NAME"
test -e keybindings.cfg && cp -alu keybindings.cfg ~/.unvanquished/config/
test -e pubkey          && cp -alu pubkey	  ~/.unvanquished/
chmod go= ~/.unvanquished/pubkey
test -e autogen.cfg && grep '^seta name ' autogen.cfg >~/.unvanquished/config/autogen.cfg

echo "Basic profile for '$NAME' has been copied into ~/.unvanquished."
echo "Some local server configuration (if present) has also been copied."
echo 'Most settings have not been transferred.'
echo 'You should check the configuration (in ~/.unvanquished).'
echo 'Anything missing is in ~/.Unvanquished, which you may remove once done.'
