#! /bin/sh
cd /usr/lib/games/unvanquished
unvanquished-migrate-profile

# Assumptions:
# - if there's a URI, it's the first parameter (after any debug options)
# - pipe file presence == Unvanquished is running
# - the pipe file's name hasn't been changed

UNVPIPE=~/.Unvanquished/main/pipe

unset RUNGDB
if test "$1" = --gdb; then
  shift
  if test -f /usr/bin/gdb; then
    RUNGDB='gdb --args'
  fi
fi

URI="$(echo "$1" | sed -e 's/%5B/[/; s/%5D/]/')"

echo "$URI" | LANG=C grep -q '^unv://\(\[[0-9A-Fa-f:]\+\]\|[-.A-Za-z0-9]\+\)\(:[0-9]\+\)\?/\?$'
NOT_URI=$?

if test -p "$UNVPIPE" && lsof "$UNVPIPE" >/dev/null 2>&1; then
  if test $NOT_URI != 0; then
    echo "$0: invalid URI: $URI" >&2
    exit 2
  fi
  # Just pass on the URI; drop the rest
  echo "connect \"$URI\"" >~/.Unvanquished/main/pipe
  exit
fi

PRECMD=
if test $NOT_URI = 0; then
  PRECMD="connect $URI"
  shift
else
  echo "$URI" | LANG=C grep -qi '^unv://'
  if test $? = 0; then
    echo "$0: invalid URI: $URI" >&2
    exit 2
  fi
fi

# Prefix with + if needed
PREFIX=+
case "$PRECMD$@" in
  +*|-*|'')
    PREFIX=
    ;;
esac

exec $RUNGDB ./unvanquished +set fs_libpath "$PWD" +set fs_basepath /var/games/unvanquished $PREFIX$PRECMD"$@"
